### ISSUE TITLE
hmmm whats wrong? error build using new method

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#1086]
```

[build] Not running inside VS Code
[build] rootPath is "/root/vc2/code-server"
[build] outPath is "/root/vc2/bin"
[build] arch is "x86_64"
[build] target is "linux"
[build] vscodeVersion is "1.39.2"
[build] codeServerVersion is "1.39.3"
[build] Installing code-server dependencies...took 966ms
[build] Cloning VS Code...took 5258ms
[build] Installing VS Code dependencies...saazzzzaaatook 355900ms
[build] Building default extensions...ccgggtook 236572ms
[build] Patching VS Code...took 1920ms
[build] Copying code-server into VS Code...took 9559ms
[build] Building VS Code...asdhhfailed
Command failed: yarn gulp compile-build --max-old-space-size=32384
[14:50:11] 'compile-build' errored after 4.53 min
[14:50:11] Error: Found 1 errors
    at Stream.<anonymous> (/root/vc2/bin/build/vscode-1.39.2-source/build/lib/reporter.js:74:29)
    at _end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:65:9)
    at Stream.stream.end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:203:15)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at drain (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:45:5)
    at Stream.end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:15:35)
    at _end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:65:9)
error Command failed with exit code 1.

```

**Comment by sr229** [comment]
We haven't updated to 1.39.x yet. Please stick to 1.38.x for now.

**Comment by Dj-jom2x** [comment]
but thats on the travis.yml  - export VSCODE_VERSION="1.39.2" can you give me specific please xD

**Comment by sr229** [comment]
This is initial groundwork for the upgrade, please DO NOT upgrade until you see our Travis build go green.

**Comment by Dj-jom2x** [comment]
I tried 1.38.1 1.38.1 but patches dint applied. the new installer is so easy tho.. than before.

to be clear I can't git clone this and run the yarn build to 1.38.1 .. I need to stick with the releases right? until it goes green?


![image](https://user-images.githubusercontent.com/12135498/67146250-d8b41f00-f2bb-11e9-8995-e67376beb21d.png)

**Comment by sr229** [comment]
Checked out the latest changes, it should compile fine now.
