### ISSUE TITLE
what causes ? createFileSystemProviderError or ERR Unknown (FileSystemError): Error: timed out

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#1149]
ERR Unknown (FileSystemError): Error: timed out
    at new t (https://demo.net:8443/ide.main.5b173b.js:16:129721)
    at Object.t.createFileSystemProviderError (https://demo.net:8443/ide.main.5b173b.js:16:130360)
    at t.toFileSystemProviderError (https://demo.net:8443/ide.main.5b173b.js:60:6383354)
    at t.<anonymous> (https://demo.net:8443/ide.main.5b173b.js:60:6376134)
    at https://demo.net:8443/ide.main.5b173b.js:16:2489
    at Object.throw (https://demo.net:8443/ide.main.5b173b.js:16:2594)
    at s (https://demo.net:8443/ide.main.5b173b.js:16:1416)

**Comment by code-asher** [comment]
Is this v1? I don't think there's an ide.main.js in v2.

**Comment by sr229** [comment]
This is v1 so closing off as deprecated
