### ISSUE TITLE
Error when start server and terminal keep starting

### ISSUE THREAD

**Issue by MuZhou233** [cdr/code-server#1194]
- `code-server` version: 2.1692-vsc1.39.2-linux-x86_64
- OS Version: Fyde OS v8.1 (Based on Chromium OS R77)

## Description

When I run code-server in crosh, it reports the following error. I can still open the page by typing `localhost:8080` in my browser. Open and edit file is okay but the terminal is keep starting.
In addition, everthing works well on Fyde OS v7 with code-server v1.
```
{ Error: /tmp/.nbinIAJjfx-spdlog.node: failed to map segment from shared object
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:754:18)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at Module.patchedRequire [as require] (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at Module.patchedRequire [as require] (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:22:18)
    at t.load (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:16:119)
    at e.load (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:13:586)
    at i (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:29:189)
    at Object.errorback (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:29:313)
    at e.triggerErrorback (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:13:955)
    at /src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:13:659
    at /src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/loader.js:16:494
    at s.readFile.then.catch.e (nbin.js:1:8680)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ] }
```

## Steps to Reproduce

1. open crosh shell (not the crostini or crouton)
1. place the binary code-server to /usr/local/bin
1. run by `code-server --auth none`

**Comment by sr229** [comment]
@MuZhou233 unable to reproduce, terminal has spawned properly on my end. Is this on Crostini or in native CrOS?

**Comment by MuZhou233** [comment]
@sr229 native CrOS，exactly is press `Tab+Alt+T` and insert `shell`.
I can`t say if the error is beacause of Fyde has changed something in the system, but before I update the OS version, everything works well.

**Comment by satwell** [comment]
I just ran into the exact same error message and hanging terminal in Docker, and it was caused by mounting /tmp as tmpfs with the noexec option.  Perhaps Fyde added noexec to /tmp?

**Comment by MuZhou233** [comment]
@satwell Thanks, It seems true that Fyde added noexec to /tmp.
```
sudo mount -o remount,exec /tmp
```
After remove the noexec flag, It doesn`t report error anymore and terminal has spawned properly.

**Comment by sr229** [comment]
@MuZhou233 @satwell I wouldn't recommend doing that as discussed in the Chromium OS mailing list, /tmp has been mounted as noexec for security purposes. Please use Crostini or Crouton to provide your environment instead of native CrOS.
