### ISSUE TITLE
Uncaught Exception color blue when running via docker

### ISSUE THREAD

**Issue by markwylde** [cdr/code-server#1226]
- `code-server` version: 2.1699-vsc1.41.0
- OS Version: Linux 4.15.0-72-generic (Ubuntu Server)

## Description

When I run the command:

```bash
docker run -it -p 8080:8080 -v "/tmp:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" codercom/code-server:v2
```

I get the following output:

```bash
root@test:/var/www# docker run -it -p 8080:8080 -v "/tmp:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" codercom/code-server:v2
info  Server listening on http://0.0.0.0:8080
info    - Password is 2af06ae00d47b6c71d65d2b2
info      - To use your own password, set the PASSWORD environment variable
info      - To disable use `--auth none`
info    - Not serving HTTPS
%c[IPC Library: File Watcher (chokidar)] %cUncaught Exception:  color: blue color:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.normalize (path.js:1117:5)
    at F (nbin.js:1:2543)
    at Object.statSync (nbin.js:1:3222)
    at stat (internal/modules/cjs/loader.js:93:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:256:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:590:25)
    at Function.Module._load (internal/modules/cjs/loader.js:519:25)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/src/build/code-server2.1699-vsc1.41.0-linux-x86_64-built/out/bootstrap-fork.js:19:362)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:778:12)
    at startup (internal/bootstrap/node.js:288:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:748:3)
```

## Steps to Reproduce

1. Run `docker run -it -p 8080:8080 -v "/tmp:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" codercom/code-server:v2`

2. Open `http://remote:8080` in your browser

3. View the docker logs to get the above message

**Comment by dntq83** [comment]
I have the same problem

**Comment by strujilloc** [comment]
same problem here. what I did is run the ` 2.1697-vsc1.39.2 `version instead of `V2`

**Comment by jesseward** [comment]
> same problem here. what I did is run the `2.1697-vsc1.39.2`version instead of `V2`

Were you able to resolve this by reverting to that version? Does anyone know then this was introduced? I am seeing it in head/master as well..

**Comment by dmin7b5** [comment]
I am seeing the same issue here. I got some additional debug info by tailing remoteagent.log
It looks like a path error to the theme extensions dir...doesn't exist.

`[2019-12-18 13:17:09.650] [remoteagent] [info] request.url "/"
[2019-12-18 13:17:10.572] [remoteagent] [error] [File Watcher (node.js)] Failed to watch /src/build/code-serverdocker-vsc1.41.0-linux-x86_64-built/extensions/theme-seti/icons/vs-seti-icon-theme.json for changes using fs.watch() (Error: ENOENT: no such file or directory, watch '/src/build/code-serverdocker-vsc1.41.0-linux-x86_64-built/extensions/theme-seti/icons/vs-seti-icon-theme.json')
[2019-12-18 13:17:10.572] [remoteagent] [error] [File Watcher (node.js)] Failed to watch /src/build/code-serverdocker-vsc1.41.0-linux-x86_64-built/extensions/theme-seti/icons/vs-seti-icon-theme.json for changes using fs.watch() (Error: ENOENT: no such file or directory, watch '/src/build/code-serverdocker-vsc1.41.0-linux-x86_64-built/extensions/theme-seti/icons/vs-seti-icon-theme.json')
[2019-12-18 13:17:10.725] [remoteagent] [error] Extension host stderr path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.normalize (path.js:1117:5)
    at F (nbin.js:1:2543)
    at Object.statSync (nbin.js:1:3222)
    at stat (internal/modules/cjs/loader.js:93:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:256:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:590:25)
    at Function.Module._load (internal/modules/cjs/loader.js:519:25)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/src/build/code-serverdocker-vsc1.41.0-linux-x86_64-built/out/bootstrap-fork.js:19:362)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:778:12)
    at startup (internal/bootstrap/node.js:288:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:748:3)`

**Comment by sr229** [comment]
Track this on #1220 instead.
