### ISSUE TITLE
blank screen when start container of code-server on centos 7

### ISSUE THREAD

**Issue by Sanyorke-Han** [cdr/code-server#1229]
on centos, I start container with below command:

```shell
sudo docker run -it -p 192.168.95.128:8080:8080 \
    -v "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server" \
    -v "$PWD:/home/coder/project" \
    codercom/code-server:v2
```
after it finished, I use another machine with chrome to go address: 
http://192.168.95.128:8080

when I entered password, it shows blank screen. then I looked at its backend, got below contents:
```txt
  ERR Error: Error: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/User'
log.ts:196   ERR Cannot read property 'get' of undefined: TypeError: Cannot read property 'get' of undefined
    at p.get (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1629:113)
    at new P (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:4442:102)
    at h._createInstance (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1446:545)
    at h._createServiceInstance (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1448:470)
    at h._createServiceInstanceWithOwner (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1448:65)
    at h._createAndCacheServiceInstance (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1447:756)
    at h._getOrCreateServiceInstance (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1447:44)
    at Object.get (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1445:604)
    at t.Workbench.initLayout (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:5255:188)
    at http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:5279:219
log.ts:196   ERR Cannot read property 'get' of undefined: TypeError: Cannot read property 'get' of undefined
    at p.get (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1629:113)
    at S._get (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3241:262)
    at S.get (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3240:614)
    at Proxy._getExtensions (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3239:512)
    at Proxy._getDisabledExtensions (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3239:304)
    at Proxy.getEnablementState (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3235:680)
    at Proxy.isEnabled (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3236:601)
    at D._isDisabled (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3229:358)
    at D._isEnabled (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3229:186)
    at http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3924:664
errors.ts:26 Uncaught Error: Error: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/User'

NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/User',    at Object.t.createFileSystemProviderError (/src/build/code-server2.1697-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/cli.js:210:809),    at t.DiskFileSystemProvider.toFileSystemProviderError (/src/build/code-server2.1697-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/cli.js:249:861),    at t.DiskFileSystemProvider.mkdir (/src/build/code-server2.1697-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/cli.js:245:963)
    at errors.ts:26
extensionsRegistry.ts:124 Uncaught Error: Handler already set!
    at u.setHandler (extensionsRegistry.ts:124)
    at g.initialize (colorThemeStore.ts:66)
    at new g (colorThemeStore.ts:62)
    at new P (workbenchThemeService.ts:105)
    at h._createInstance (instantiationService.ts:117)
    at h._createServiceInstance (instantiationService.ts:216)
    at h._createServiceInstanceWithOwner (instantiationService.ts:205)
    at h._createAndCacheServiceInstance (instantiationService.ts:194)
    at h._getOrCreateServiceInstance (instantiationService.ts:142)
    at h._createInstance (instantiationService.ts:94)
log.ts:196   ERR Cannot read property 'get' of undefined: TypeError: Cannot read property 'get' of undefined
    at p.get (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1629:113)
    at W (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1802:239)
    at new z (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1793:270)
    at h._createInstance (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1446:545)
    at http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:1448:331
    at t.IdleValue._executor (http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:151:219)
    at http://192.168.95.128:8080/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:151:308
layout.ts:826 Uncaught TypeError: Cannot read property 'layout' of undefined
    at t.Workbench.layout (layout.ts:826)
    at web.main.ts:94
extensionHostProcessManager.ts:77 Error received from starting extension host
(anonymous) @ extensionHostProcessManager.ts:77
extensionHostProcessManager.ts:78 timeout
```

**Comment by bruce9399** [comment]
try this

chown 1000:1000 ${HOME}/.local/share/code-server -R
sudo docker run -it -p 192.168.95.128:8080:8080 \
    -v "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server" \
    -v "$PWD:/home/coder/project" \
    --privileged=true \
    codercom/code-server:v2

**Comment by Sanyorke-Han** [comment]
yes, this works. 
thanks a lot.

**Comment by Orbis36** [comment]
@bruce9399  Thanks a lot !!
