### ISSUE TITLE
Error: Unknown option --host=0.0.0.0 ?!

### ISSUE THREAD

**Issue by theraw** [cdr/code-server#1361]
Just tried to run docker container as your readme says

```bash
root@dopeplesk:/var/www/vhosts/example.com/# docker run -it -p 127.0.0.1:8080:7788 -v "$PWD:/home/coder/project" codercom/code-server
/repo/build/out/node/cli.js:115
                throw new Error("Unknown option " + arg);
                ^

Error: Unknown option --host=0.0.0.0
    at _loop_1 (/repo/build/out/node/cli.js:115:23)
    at Object.exports.parse (/repo/build/out/node/cli.js:177:9)
    at Object.<anonymous> (/repo/build/out/node/entry.js:170:18)
    at Module._compile (internal/modules/cjs/loader.js:976:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1018:10)
    at Module.load (internal/modules/cjs/loader.js:832:32)
    at Function.Module._load (internal/modules/cjs/loader.js:744:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1101:10)
    at _third_party_main.js:11:19
    at NativeModule.compile (internal/bootstrap/loaders.js:285:5)
```

inspect
```bash
[
    {
        "Id": "10ab30210e74197560b6a3d8506efac97f1a1543a2ca88dbe9ae39e1849dd9a0",
        "Created": "2020-02-19T05:04:35.325188119Z",
        "Path": "dumb-init",
        "Args": [
            "fixuid",
            "-q",
            "code-server",
            "--host=0.0.0.0",
            "--auth=none"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2020-02-19T05:04:36.103632151Z",
            "FinishedAt": "2020-02-19T05:04:36.455648152Z"
        },
```

**Comment by nhooyr** [comment]
Sorry, accidents pushed a pre release on CI.

Fixing.

**Comment by nhooyr** [comment]
Fixed.

**Comment by theraw** [comment]
thanks for quick response feel free to close issue as you see fit
