### ISSUE TITLE
code-server exit automatically.

### ISSUE THREAD

**Issue by ladyrick** [cdr/code-server#1412]
```
[IPC Library: File Watcher (chokidar)] Unhandled Promise Rejection:  Canceled: Canceled
    at Object.canceled (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/out/vs/platform/files/node/watcher/unix/watcherApp.js:111:23)
    at Delayer.cancel (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/out/vs/platform/files/node/watcher/unix/watcherApp.js:2320:38)
    at ThrottledDelayer.cancel (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/out/vs/platform/files/node/watcher/unix/watcherApp.js:2356:26)
    at Object.stop (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/out/vs/platform/files/node/watcher/unix/watcherApp.js:12182:46)
    at ChokidarWatcherService.stop (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/out/vs/platform/files/node/watcher/unix/watcherApp.js:12286:25)
    at FSWatcher.<anonymous> (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/out/vs/platform/files/node/watcher/unix/watcherApp.js:12272:34)
    at FSWatcher.emit (events.js:210:5)
    at FSWatcher._handleError (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/index.js:625:10)
    at NodeFsHandler._boundHandleError (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/lib/nodefs-handler.js:302:43)
    at createFsWatchInstance (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/lib/nodefs-handler.js:120:5)
    at setFsWatchListener (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/lib/nodefs-handler.js:165:15)
    at NodeFsHandler._watchWithNodeFs (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/lib/nodefs-handler.js:330:14)
    at NodeFsHandler._handleFile (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/lib/nodefs-handler.js:360:23)
    at NodeFsHandler._addToNodeFs (/code-server/build/code-serverdaily-vsc1.41.1-linux-x86_64-built/node_modules/chokidar/lib/nodefs-handler.js:620:21)
```
What happened? I was editing a file and it just exited. Please help me. Thank you.

**Comment by code-asher** [comment]
Are there any more logs? I'm not sure this error would have caused
code-server to exit so there might be another error somewhere.

Do you know if this happens on the latest v3 pre-release?

**Comment by ladyrick** [comment]
No other logs...
stderr only showed these logs. stdout showed nothing..

I used my self-built version. The only thing I modified is to remove "samesite:strict" in cookie.

**Comment by code-asher** [comment]
Do you have the same problem if you build off latest master?

**Comment by jamaalscarlett** [comment]
I get  this error when I try and build my c project using mock.

**Comment by kylecarbs** [comment]
Closing for now.

Happy to provide some help. Please make sure you're on the latest release of code-server.

**Comment by jamaalscarlett** [comment]
@kylecarbs I just deployed that latest container and I am still seeing this.  Could the issue be the handling of a large number of files to the project dir/subdirectory?  As I said in my previous comment, the issue occurs when I start building the project using Mock, which creates a chroot, and uses that to build an RPM.

**Comment by kylecarbs** [comment]
Weird weird. Shouldn't be. How many files do you have in that dir?

**Comment by jamaalscarlett** [comment]
@kylecarbs 561 files and subdirectories in the build directory that is created

**Comment by nhooyr** [comment]
Yea that's definitely not enough to cause this behaviour. There's also a proper error message for when there are too many files to watch.

**Comment by nhooyr** [comment]
Has this still been happening to you guys?

**Comment by jamaalscarlett** [comment]
I have reverted to my previous setup of rsync and ssh, butI will deploy the latest and report back.

**Comment by sap471** [comment]
try to increase system file watcher

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

it's work for me

**Comment by jamaalscarlett** [comment]
This worked for code-server running directly on my VM, but I am still seeing the crash when running the docker container.

**Comment by Alababdiy** [comment]
same problem
