### ISSUE TITLE
Service itself stop

### ISSUE THREAD

**Issue by seeidea** [cdr/code-server#1433]
version: 2.1698-vsc1.41.1
system: CentOS Linux release 7.7.1908
command:  nohup ./code-server --user-data-dir=/vscodeserver/data --port=8888 --auth=none > nohup.log 2>&1 &

There is no error reporting a service stop in the log

Nohup logs are only available

nohup: ignoring input
info  Server listening on http://localhost:8888
info    - No authentication
info    - Not serving HTTPS

data/logs logs are only available

[2020-03-18 10:24:04.304] [remoteagent] [info] update#setState idle
[2020-03-18 11:13:44.300] [remoteagent] [info] request.url "/"
[2020-03-18 11:24:04.256] [remoteagent] [info] update#setState checking for updates
[2020-03-18 11:24:05.771] [remoteagent] [error] Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
[2020-03-18 11:24:05.771] [remoteagent] [info] update#setState idle
[2020-03-18 12:24:04.258] [remoteagent] [info] update#setState checking for updates
[2020-03-18 12:24:04.455] [remoteagent] [error] Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
[2020-03-18 12:24:04.455] [remoteagent] [info] update#setState idle
[2020-03-18 12:39:39.023] [remoteagent] [info] request.url "http://clientapi.ipip.net/echo.php?info=1234567890"
[2020-03-18 13:24:04.273] [remoteagent] [info] update#setState checking for updates
[2020-03-18 13:24:05.469] [remoteagent] [error] Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
[2020-03-18 13:24:05.469] [remoteagent] [info] update#setState idle
[2020-03-18 13:25:38.922] [remoteagent] [info] request.url "/"

These logs do not cause service to crash

Please give advice or comments

**Comment by kylecarbs** [comment]
Just to make sure, code-server doesn't quit, right?

**Comment by seeidea** [comment]
Thank you for your reply. It has been determined that the reason for the exception to stop is that using nohup did not exit the command line normally
