### ISSUE TITLE
Code-server does not open while accessing via Tunnelin

### ISSUE THREAD

**Issue by aravindharinair** [cdr/code-server#1441]
I've set up an old box with Ubuntu Server installed on it and running code-server. Able to access via ngrok (tried on local network). But when running via Tunnelin (for standardised domain availability), the logs throw this up:
```
(node:20198) UnhandledPromiseRejectionWarning: Error: Reconnection token is missing from query parameters
    at t.Vscode.handleWebSocket (/home/frost/code-server-3.0.0-linux-x86_64/lib/vscode/out/vs/server/entry.js:405:428)
    at process.<anonymous> (/home/frost/code-server-3.0.0-linux-x86_64/lib/vscode/out/vs/server/entry.js:411:246)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:20198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a pr
omise which was not handled with .catch(). (rejection id: 1)
(node:20198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non
-zero exit code.
```

**Comment by nhooyr** [comment]
What is Tunnelin?

**Comment by aravindharinair** [comment]
[TunnelIn ](https://app.tunnelin.com/) is a tunneling provider similar to ngrok but free, unlike ngrok.

**Comment by kylecarbs** [comment]
They might be stripping GET params? Could you MITM the request before it hits code-server?

**Comment by aravindharinair** [comment]
How do you suggest I go about that?

**Comment by kylecarbs** [comment]
Sorry for the super slow response. From your browser make sure that the GET param exists when the websocket is connecting, and that should be a good first step.

**Comment by kylecarbs** [comment]
Closing for now. Happy to hear back though if you're able to debug this!
