### ISSUE TITLE
crash if refresh

### ISSUE THREAD

**Issue by jf3096** [cdr/code-server#1462]
verbose info showing below:

```bash
Message from syslogd@iZwz9d2a0en8qwrd5p1l2qZ at Mar 30 01:39:58 ...
 kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

```

**Comment by nhooyr** [comment]
>  kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1

Is that from code-server?

**Comment by kylecarbs** [comment]
Closing for now. Please follow up if this is still a problem @jf3096 !
