### ISSUE TITLE
Error loading markdownlint extension

### ISSUE THREAD

**Issue by ctlajoie** [cdr/code-server#1593]
I experienced this with the `davidanson.vscode-markdownlint` extension but it could easily apply to others as well.

```
[2020-05-01 23:56:15.915] [exthost] [info] ExtensionService#_doActivateExtension DavidAnson.vscode-markdownlint {"startup":false,"extensionId":{"value":"DavidAnson.vscode-markdownlint","_lower":"davidanson.vscode-markdownlint"},"activationEvent":"onLanguage:markdown"}
[2020-05-01 23:56:15.915] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.local/share/code-server/extensions/davidanson.vscode-markdownlint-0.35.1/bundle
[2020-05-01 23:56:15.916] [exthost] [error] Activating extension DavidAnson.vscode-markdownlint failed due to an error:
[2020-05-01 23:56:15.918] [exthost] [error] Error: Cannot find module '/home/coder/.local/share/code-server/extensions/davidanson.vscode-markdownlint-0.35.1/bundle'
Require stack:
- /usr/local/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/local/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/lib/code-server/lib/vscode/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
	at Function.Module._load (internal/modules/cjs/loader.js:840:27)
	at Function.t._load (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:920:599)
	at Function.i._load (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:889:759)
	at Function.n._load (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:886:63)
	at Module.require (internal/modules/cjs/loader.js:1019:19)
	at require (internal/modules/cjs/helpers.js:77:18)
	at Function.s [as __$__nodeRequire] (/usr/local/lib/code-server/lib/vscode/out/vs/loader.js:32:963)
	at p._loadCommonJSModule (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:890:966)
	at p._doActivateExtension (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:856)
	at p._activateExtension (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:787:937)
	at Object.actualActivateExtension (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:883)
	at e._activateExtension (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:566:859)
	at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:566:537
	at Array.map (<anonymous>)
	at e._activateExtensions (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:566:525)
	at e.activateByEvent (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:14)
	at p._activateByEvent (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:786:618)
	at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:795:159
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This seems to be caused by the absence of a .js file extension. I downloaded the vsix file and in the package.json there is the following key:
```
    "main": "./bundle",
```
If I add a `.js` to this, the extension loads fine.

This does not happen in vscode.

**Comment by cmoog** [comment]
Thank you for bringing this to our attention. The issue is now resolved. If you reinstall the extension everything should work properly. 

Let me know if you still have issues and I'll reopen this.

**Comment by ctlajoie** [comment]
@cmoog @nhooyr Is there an alternative solution that I can pursue for this? If the problem really is simply the absence of a `.js` file extension on the `main` property in package.json, perhaps they would be willing to accept a PR with this modification.

**Comment by code-asher** [comment]
I think the problem is that our marketplace is trying to build the
extension but fails. It tries various commands like `yarn build` but it
looks like this extension uses `yarn compile` and I'm not sure our
marketplace tries that one.

Workarounds would be to build the vsix manually since they don't include
releases on their GitHub or download it from Open VSX:
https://open-vsx.org/extension/DavidAnson/vscode-markdownlint

Since we're deprecating our marketplace in favor of Open VSX it's
possible we won't fix this in our marketplace.
