### ISSUE TITLE
Terminal not loading

### ISSUE THREAD

**Issue by vafanassieff** [cdr/code-server#1629]
Hey there, i'm having issues loading a new terminal, sometimes it work, if open 6 terminal in a row and sometimes it doesnt.

I've tried to switch between sh / bash / zsh, only sh "works sometimes".

Here is the logs when i open a new terminal, i've just redacted the domain name.

` ERR Cannot read property 'toString' of undefined: TypeError: Cannot read property 'toString' of undefined
    at a (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/node_modules/xterm/lib/xterm.js:1:10447)
    at Object.e.toCss (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/node_modules/xterm/lib/xterm.js:1:10659)
    at e._parseColor (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/node_modules/xterm/lib/xterm.js:1:43447)
    at e.setTheme (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/node_modules/xterm/lib/xterm.js:1:41289)
    at t.open (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/node_modules/xterm/lib/xterm.js:1:71724)
    at e.open (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/node_modules/xterm/lib/xterm.js:1:52921)
    at e._attachToElement (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/out/vs/workbench/workbench.web.api.js:4172:996)
workbench.web.api.js:sourcemap:1554   ERR Cannot read property '_onIntersectionChange' of undefined: TypeError: Cannot read property '_onIntersectionChange' of undefined
    at e._resize (https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/out/vs/workbench/workbench.web.api.js:4189:399)
    at https://{DOMAIN}/static/fd36a99a4c78669970ebc4eb05768293b657716f/lib/vscode/out/vs/workbench/workbench.web.api.js:44:876`

Best

**Comment by fbriol** [comment]
I'm also affected by this problem.

**Comment by nhooyr** [comment]
Can you guys try the latest release?

**Comment by fbriol** [comment]
I still have the same problem with the latest version.

**Comment by nhooyr** [comment]
Must be #1659 or #1640 

Will look into it tomorrow morning.

**Comment by fbriol** [comment]
OK. Thanks.

**Comment by gauravk88** [comment]
> Must be #1659 or #1640
> 
> Will look into it tomorrow morning.

I looked into this as my terminal was also not opening on rhel7.
I was able to trace it down to libstdc++ being ancient. So i upgraded to a newer one and it was fine after that.

**Comment by nhooyr** [comment]
Closing for inactivity and should be fixed anyway.

**Comment by vafanassieff** [comment]
Confirmed it's fixed for me now, thanks !

**Comment by fbriol** [comment]
For your information, I always had this problem even with the latest versions. As I was the only one, I tried to find out why. The origin of the problem is that I was running the server in a Conda environment. This causes a confit in the libraries and makes the terminal unusable.
