### ISSUE TITLE
VS code refreshes repetadly

### ISSUE THREAD

**Issue by fennectech** [cdr/code-server#1649]
VS Code starts perfectly fine when i launch the application  but when i attempt to connect to it from any device  it gets into a loop of refreshing over and over   I am on arch linux and i installed with https://aur.archlinux.org/packages/code-server/ this package
Thank you for helping
```
[fennectech@jasper ~]$  /opt/code-server/code-server --bind-addr 10.0.0.20:8080 -vvv
debug spawned inner process 2674343
debug parsed command line {"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true}}
debug wrapper 2674332 received message from 2674343 {"message":{"type":"handshake"}}
debug inner process 2674343 received message from 2674332 {"message":{"type":"handshake"}}
info  code-server 3.2.0 fd36a99a4c78669970ebc4eb05768293b657716f
info  HTTP server listening on http://10.0.0.20:8080
info    - Using custom password for authentication
info    - Not serving HTTPS
info  Automatic updates are enabled
trace heartbeat
debug forking vs code...
debug got message from vs code {"message":{"type":"ready"}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"g1DAn4vmA9owhnQv7Ph26bHB","options":{"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true,"log":"trace","user-data-dir":"/home/fennectech/.local/share/code-server","extensions-dir":"/home/fennectech/.local/share/code-server/extensions"},"remoteAuthority":"fennectech.n4t.co:8080","startPath":{"url":"/home/fennectech/switch-dev/deepsea.code-workspace","workspace":true}}}}
[server] storing proxy {"proxyId":"child_process"}
[server] storing proxy {"proxyId":"fs"}
[server] storing proxy {"proxyId":"net"}
debug got message from vs code {"message":{"type":"options","id":"g1DAn4vmA9owhnQv7Ph26bHB","options":{"workbenchWebConfiguration":{"workspaceUri":{"$mid":1,"path":"/home/fennectech/switch-dev/deepsea.code-workspace","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"remoteAuthority":"fennectech.n4t.co:8080","logLevel":0,"workspaceProvider":{"payload":[["userDataPath","/home/fennectech/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/fennectech/.local/share/code-server","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.references-view"],"commit":"fd36a99a4c78669970ebc4eb05768293b657716f","date":"2020-04-29T20:40:08.161Z","version":"1.44.2","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"fd36a99a4c78669970ebc4eb05768293b657716f"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"46c7b34f-47e1-47c2-9f12-036c082bb277","reconnection":"false","skipWebSocketFrames":"false"}}}
debug got latest version {"latest":"3.2.0"}
debug comparing versions {"current":"3.2.0","latest":"3.2.0"}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"215265d0-71a9-415c-b9c6-78debba4dcd5","reconnection":"false","skipWebSocketFrames":"false"}}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"SYlf8t8jPGoAvic4WvupfdSI","options":{"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true,"log":"trace","user-data-dir":"/home/fennectech/.local/share/code-server","extensions-dir":"/home/fennectech/.local/share/code-server/extensions"},"remoteAuthority":"fennectech.n4t.co:8080","startPath":{"url":"/home/fennectech/switch-dev/deepsea.code-workspace","workspace":true}}}}
debug got message from vs code {"message":{"type":"options","id":"SYlf8t8jPGoAvic4WvupfdSI","options":{"workbenchWebConfiguration":{"workspaceUri":{"$mid":1,"path":"/home/fennectech/switch-dev/deepsea.code-workspace","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"remoteAuthority":"fennectech.n4t.co:8080","logLevel":0,"workspaceProvider":{"payload":[["userDataPath","/home/fennectech/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/fennectech/.local/share/code-server","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.references-view"],"commit":"fd36a99a4c78669970ebc4eb05768293b657716f","date":"2020-04-29T20:40:08.161Z","version":"1.44.2","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"fd36a99a4c78669970ebc4eb05768293b657716f"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"58fea564-b8be-45b4-a956-e68ba568e69d","reconnection":"false","skipWebSocketFrames":"false"}}}
[server] disconnected from client {"proxies":3}
debug got latest version {"latest":"3.2.0"}
debug comparing versions {"current":"3.2.0","latest":"3.2.0"}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"96bb9126-fb50-4757-840f-2971e50fd44b","reconnection":"false","skipWebSocketFrames":"false"}}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"KC05RXLvgS1lOXCEpAWPI2To","options":{"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true,"log":"trace","user-data-dir":"/home/fennectech/.local/share/code-server","extensions-dir":"/home/fennectech/.local/share/code-server/extensions"},"remoteAuthority":"fennectech.n4t.co:8080","startPath":{"url":"/home/fennectech/switch-dev/deepsea.code-workspace","workspace":true}}}}
debug got message from vs code {"message":{"type":"options","id":"KC05RXLvgS1lOXCEpAWPI2To","options":{"workbenchWebConfiguration":{"workspaceUri":{"$mid":1,"path":"/home/fennectech/switch-dev/deepsea.code-workspace","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"remoteAuthority":"fennectech.n4t.co:8080","logLevel":0,"workspaceProvider":{"payload":[["userDataPath","/home/fennectech/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/fennectech/.local/share/code-server","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.references-view"],"commit":"fd36a99a4c78669970ebc4eb05768293b657716f","date":"2020-04-29T20:40:08.161Z","version":"1.44.2","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"fd36a99a4c78669970ebc4eb05768293b657716f"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"62ba6ec7-2ddc-4987-8c99-3a5eff187548","reconnection":"false","skipWebSocketFrames":"false"}}}
[server] reconnected to client
[server] disconnected from client {"proxies":3}
debug got latest version {"latest":"3.2.0"}
debug comparing versions {"current":"3.2.0","latest":"3.2.0"}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"4fed0b06-cb0a-4455-88f6-030b8832ab13","reconnection":"false","skipWebSocketFrames":"false"}}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"dDbBVXvosyYxIHFdEjfwPbgo","options":{"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true,"log":"trace","user-data-dir":"/home/fennectech/.local/share/code-server","extensions-dir":"/home/fennectech/.local/share/code-server/extensions"},"remoteAuthority":"fennectech.n4t.co:8080","startPath":{"url":"/home/fennectech/switch-dev/deepsea.code-workspace","workspace":true}}}}
debug got message from vs code {"message":{"type":"options","id":"dDbBVXvosyYxIHFdEjfwPbgo","options":{"workbenchWebConfiguration":{"workspaceUri":{"$mid":1,"path":"/home/fennectech/switch-dev/deepsea.code-workspace","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"remoteAuthority":"fennectech.n4t.co:8080","logLevel":0,"workspaceProvider":{"payload":[["userDataPath","/home/fennectech/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/fennectech/.local/share/code-server","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.references-view"],"commit":"fd36a99a4c78669970ebc4eb05768293b657716f","date":"2020-04-29T20:40:08.161Z","version":"1.44.2","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"fd36a99a4c78669970ebc4eb05768293b657716f"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"59416fbf-f2fa-47e6-a7b6-329fd779f682","reconnection":"false","skipWebSocketFrames":"false"}}}
[server] reconnected to client
[server] disconnected from client {"proxies":3}
debug got latest version {"latest":"3.2.0"}
debug comparing versions {"current":"3.2.0","latest":"3.2.0"}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"179db3eb-a806-4d39-9c22-3d95fbea1a10","reconnection":"false","skipWebSocketFrames":"false"}}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"9b99Va2k1AI9A14o9YcllDfN","options":{"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true,"log":"trace","user-data-dir":"/home/fennectech/.local/share/code-server","extensions-dir":"/home/fennectech/.local/share/code-server/extensions"},"remoteAuthority":"fennectech.n4t.co:8080","startPath":{"url":"/home/fennectech/switch-dev/deepsea.code-workspace","workspace":true}}}}
debug got message from vs code {"message":{"type":"options","id":"9b99Va2k1AI9A14o9YcllDfN","options":{"workbenchWebConfiguration":{"workspaceUri":{"$mid":1,"path":"/home/fennectech/switch-dev/deepsea.code-workspace","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"remoteAuthority":"fennectech.n4t.co:8080","logLevel":0,"workspaceProvider":{"payload":[["userDataPath","/home/fennectech/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/fennectech/.local/share/code-server","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.references-view"],"commit":"fd36a99a4c78669970ebc4eb05768293b657716f","date":"2020-04-29T20:40:08.161Z","version":"1.44.2","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"fd36a99a4c78669970ebc4eb05768293b657716f"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"a847acfc-aefb-4dc4-98ba-4aa119bc7262","reconnection":"false","skipWebSocketFrames":"false"}}}
[server] reconnected to client
[server] disconnected from client {"proxies":3}
debug got latest version {"latest":"3.2.0"}
debug comparing versions {"current":"3.2.0","latest":"3.2.0"}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"81571114-cecf-41fb-8e23-0a58de01ea58","reconnection":"false","skipWebSocketFrames":"false"}}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"oY4JbbM0zdy8IjNsPntMMkIN","options":{"args":{"_":[],"bind-addr":"10.0.0.20:8080","verbose":true,"log":"trace","user-data-dir":"/home/fennectech/.local/share/code-server","extensions-dir":"/home/fennectech/.local/share/code-server/extensions"},"remoteAuthority":"fennectech.n4t.co:8080","startPath":{"url":"/home/fennectech/switch-dev/deepsea.code-workspace","workspace":true}}}}
debug got message from vs code {"message":{"type":"options","id":"oY4JbbM0zdy8IjNsPntMMkIN","options":{"workbenchWebConfiguration":{"workspaceUri":{"$mid":1,"path":"/home/fennectech/switch-dev/deepsea.code-workspace","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"remoteAuthority":"fennectech.n4t.co:8080","logLevel":0,"workspaceProvider":{"payload":[["userDataPath","/home/fennectech/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/fennectech/.local/share/code-server","scheme":"vscode-remote","authority":"fennectech.n4t.co:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.references-view"],"commit":"fd36a99a4c78669970ebc4eb05768293b657716f","date":"2020-04-29T20:40:08.161Z","version":"1.44.2","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"fd36a99a4c78669970ebc4eb05768293b657716f"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"c5dd2760-ed8d-4294-a601-1b4dae8d93bb","reconnection":"false","skipWebSocketFrames":"false"}}}
[server] reconnected to client
[server] disconnected from client {"proxies":3}
debug got latest version {"latest":"3.2.0"}
debug comparing versions {"current":"3.2.0","latest":"3.2.0"}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"8f450fa4-d074-4210-982c-32924e2f5780","reconnection":"false","skipWebSocketFrames":"false"}}}
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error VS Code exited unexpectedly with code 1

-->

```

**Comment by fennectech** [comment]
https://github.com/Team-Neptune/DeepSea-Updater
https://github.com/Team-Neptune/DeepSea-Toolbox

Im running into the thing when ether of these two repos are in a .code-workspace file

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1581

Will have a new release out today.

**Comment by nhooyr** [comment]
Released https://github.com/cdr/code-server/releases/tag/v3.3.0!
