### ISSUE TITLE
3.3.0 version error when accessing

### ISSUE THREAD

**Issue by silenceleaf** [cdr/code-server#1658]
```
May 17 20:50:53 vm2 code-server[89389]: Error: The module '/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/spdlog/build/Release/spdlog.node'
May 17 20:50:53 vm2 code-server[89389]: was compiled against a different Node.js version using
May 17 20:50:53 vm2 code-server[89389]: NODE_MODULE_VERSION 83. This version of Node.js requires
May 17 20:50:53 vm2 code-server[89389]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
May 17 20:50:53 vm2 code-server[89389]: the module (for instance, using `npm rebuild` or `npm install`).
May 17 20:50:53 vm2 code-server[89389]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
May 17 20:50:53 vm2 code-server[89389]:     at Module.load (internal/modules/cjs/loader.js:977:32)
May 17 20:50:53 vm2 code-server[89389]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
May 17 20:50:53 vm2 code-server[89389]:     at Module.require (internal/modules/cjs/loader.js:1019:19)
May 17 20:50:53 vm2 code-server[89389]:     at Module.patchedRequire [as require] (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
May 17 20:50:53 vm2 code-server[89389]:     at require (internal/modules/cjs/helpers.js:77:18)
May 17 20:50:53 vm2 code-server[89389]:     at bindings (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/spdlog/node_modules/bindings/bindings.js:112:48)
May 17 20:50:53 vm2 code-server[89389]:     at Object.<anonymous> (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/spdlog/index.js:3:35)
May 17 20:50:53 vm2 code-server[89389]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
May 17 20:50:53 vm2 code-server[89389]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
May 17 20:50:53 vm2 code-server[89389]:     at Module.load (internal/modules/cjs/loader.js:977:32)
May 17 20:50:53 vm2 code-server[89389]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
May 17 20:50:53 vm2 code-server[89389]:     at Module.require (internal/modules/cjs/loader.js:1019:19)
May 17 20:50:53 vm2 code-server[89389]:     at Module.patchedRequire [as require] (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
May 17 20:50:53 vm2 code-server[89389]:     at require (internal/modules/cjs/helpers.js:77:18)
May 17 20:50:53 vm2 code-server[89389]:     at t.load (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:16:119)
May 17 20:50:53 vm2 code-server[89389]:     at e.load (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:13:586)
May 17 20:50:53 vm2 code-server[89389]:     at i (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:29:259)
May 17 20:50:53 vm2 code-server[89389]:     at Object.errorback (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:29:383)
May 17 20:50:53 vm2 code-server[89389]:     at e.triggerErrorback (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:13:955)
May 17 20:50:53 vm2 code-server[89389]:     at /home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:13:659
May 17 20:50:53 vm2 code-server[89389]:     at ReadFileContext.callback (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:16:494)
May 17 20:50:53 vm2 code-server[89389]:     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13) {
May 17 20:50:53 vm2 code-server[89389]:   phase: 'loading',
May 17 20:50:53 vm2 code-server[89389]:   moduleId: 'spdlog',
May 17 20:50:53 vm2 code-server[89389]:   neededBy: [ '===anonymous3===' ]
May 17 20:50:53 vm2 code-server[89389]: }
```

It can start without error.
But when accessing, printing error like above.

I am not using any package manager, I unzip it and run the code-server like before.

**Comment by dntq83** [comment]
It's the same issue #1656

**Comment by nhooyr** [comment]
It seems to be a different reported error. Looks like you're using node 12 and not using the bundled node which is node 14.

Use the `bin/code-server` script to run and it'll use bundled node which is at `lib/node`.
