### ISSUE TITLE
Document libcxx requirement

### ISSUE THREAD

**Issue by pwwang** [cdr/code-server#1706]
I only have 2.17 on RedHatEnterpriseServer 7.7, which runs code-server 3.2.0 perfectly.

However, it started to crash after the upgrade (to 3.3.0 and 3.3.1). Is it because of vscode upgrade or code-server that leverages the minimal version of glibc?

Below is the crash log:
```node console
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /path/to/code-server-3.3.1-linux-x86_64/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at Module.patchedRequire [as require] (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:73:18)
    at bindings (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/node_modules/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at Module.patchedRequire [as require] (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:73:18)
    at t.load (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:16:119)
    at e.load (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:13:586)
    at i (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:29:259)
    at Object.errorback (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:29:383)
    at e.triggerErrorback (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:13:955)
    at /path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:13:659
    at ReadFileContext.callback (/path/to/code-server-3.3.1-linux-x86_64/lib/vscode/out/vs/loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:260:13) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

```

BTW, I don't have privileges to upgrade glibc on the server.

**Comment by nhooyr** [comment]
Sorry about this, I forgot to document libcxx requirement. libc is different from libcxx.

I'll be sure to document this. In the meantime you can use the `npm` package. See the instructions in the README.

**Comment by nhooyr** [comment]
Good news we're gonna make it static in regards to libstdcxx!

So next release won't even depend on it and only depend on libc.

**Comment by pwwang** [comment]
Cool, thank you!
