### ISSUE TITLE
Some popular extensions (eg GitHub Pull Requests and Issues) fail on load due to lack of Proposed API support

### ISSUE THREAD

**Issue by aderk** [cdr/code-server#1744]
Expected behavior: Extensions load w/o error, eg GitHub.vscode-pull-request-github
Actual behavior: Extensions fail to load with the following error. 

Ideas for fixing:
1) hardcode --enable-proposed-api flag for vscode (to enable for all extensions).
2) I believe issue #1528 could also fix this by adding the flag to VSCODE_OPTIONS once it exists.

```
[2020-05-28 10:24:10.809] [exthost] [error] Error: [GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
        at a (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:810)
	at Object.t.checkProposedApiEnabled (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:148)
	at Object.registerDecorationProvider (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:906:76)
	at new t.PullRequestsTreeDataProvider (/usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:547205)
	at /usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:653078
	at Generator.next (<anonymous>)
	at /usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:650859
	at new Promise (<anonymous>)
	at n (/usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:650607)
	at t.activate (/usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:652378)
	at Function._callActivateOptional (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:825:502)
	at Function._callActivate (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:825:153)
	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824:94
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 0)
```

- Web Browser: Chrome
- Local OS: Ubuntu
- Remote OS: Ubuntu
- Remote Architecture: AMD64
- `code-server --version`: 3.3.1 6f1309795e1cb930edba68cdc7c3dcaa01da0ab3

**Comment by aderk** [comment]
If you can point me in the right direction, I'm happy to try to implement option #1 with a PR. I'm getting lost between all the Args dataclasses and wondering if I need to wrangle through the `vscode.patch`. Thanks!

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by aderk** [comment]
@code-asher Let me know if I can help out at all!

**Comment by aderk** [comment]
I attempted option 1 to no avail in PR #1779. The arguments seem accepted, but the same error (above) persists. I also tried enabling dev mode with the VSCODE_DEV env variable set to '1' or 'true' or '', which also didn't prevent the error. I'm not sure how to debug or move forward, if you have any tips!

**Comment by code-asher** [comment]
I'm not sure why it didn't automatically close but this is fixed by https://github.com/cdr/code-server/pull/2002. We're working on getting a new release out.

**Comment by nhooyr** [comment]
Reopening and will close when new release is cut.

**Comment by nhooyr** [comment]
v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!
