### ISSUE TITLE
Extension Request - phpcs

### ISSUE THREAD

**Issue by rabidsloth** [cdr/code-server#1777]
- [ ] Extension name: phpcs
- [ ] Extension GitHub or homepage: https://github.com/ikappas/vscode-phpcs

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.

**Comment by draganescu** [comment]
Howdy I am trying to use phpcs on code-server and it crashes with:

```
Error: Cannot find module '/root/.local/share/code-server/extensions/ikappas.phpcs-1.0.5/server/src/server.js'
Require stack:
- /root/.local/share/code-server/extensions/ikappas.phpcs-1.0.5/node_modules/vscode-languageclient/lib/utils/electronForkStart.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Server.<anonymous> (/root/.local/share/code-server/extensions/ikappas.phpcs-1.0.5/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at Server.emit (events.js:315:20)
    at Pipe.onconnection (net.js:1555:8) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.local/share/code-server/extensions/ikappas.phpcs-1.0.5/node_modules/vscode-languageclient/lib/utils/electronForkStart.js'
  ]
}
[Info  - 4:45:52 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:968
  throw err;
  ^
```

**Comment by code-asher** [comment]
Looks like the extension isn't building correctly. I opened https://github.com/cdr/code-server/issues/2571
