### ISSUE TITLE
code-server build python error

### ISSUE THREAD

**Issue by stakeswky** [cdr/code-server#1827]
OS:ubuntu18.04
ms-python:2019.3.6558
When I install the code-server success and build ms-python,I can't set interpreter in lastest ms-python.So I install the ms-python-2019.3.6558,I can set interpreter,but the debugger error.
![image](https://user-images.githubusercontent.com/64798754/85488467-e8c98e80-b600-11ea-9bd7-0207b123e2c9.png)

Debugger Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
Debugger Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
Error
Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
    at u (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:39000)
    at Object.t.getDependencies (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:39679)
    at /home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:36714
    at Array.forEach (<anonymous>)
    at e (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:36528)
    at Object.t.plan (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:36812)
    at /home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:33700
    at e._get (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:33609)
    at e.get (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:16:32300)
    at s.get (/home/admin_ass_ink/.local/share/code-server/extensions/ms-python.python-2019.3.6558/out/client/debugger/debugAdapter/main.js:76:102000)

Please help me!

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1821

**Comment by alan-he** [comment]
Codeserver v3.4.1 + ms-python 2020.5.86806 still get Debugger Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.
