### ISSUE TITLE
[IPC Library: File Watcher (nsfw)] Error: dlopen failed: cannot locate symbol 

### ISSUE THREAD

**Issue by yozman** [cdr/code-server#1879]
- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

run on termux
```sh
$ uname -a
Linux localhost 4.14.83-perf+ #1 SMP PREEMPT Wed May 6 14:25:36 CST 2020 aarch64 Android
```

error message
```sh
[IPC Library: File Watcher (nsfw)] Error: dlopen failed: cannot locate symbol "_ZN14InotifyServiceC1ENSt6__ndk110shared_ptrI10EventQueueEENS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" referenced by "/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-nsfw/build/Release/nsfw.node"...                                                            at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)                                           at Module.load (internal/modules/cjs/loader.js:1049:32)    at Function.Module._load (internal/modules/cjs/loader.js:937:14)                                                      at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)         at Object.<anonymous> (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-nsfw/lib/src/index.js:3:16)                  at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)                                             at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at t.load (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:16:119)
    at e.load (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:586)
    at i (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:29:259)
    at Object.errorback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:29:383)
    at e.triggerErrorback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:955)
    at /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:659
    at ReadFileContext.callback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:260:13)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
error VS Code exited unexpectedly with code 1
```

code-server --version
```sh
3.4.1
```

**Comment by code-asher** [comment]
Interesting, this is different from the errors we've been running into on Termux/Android. https://github.com/cdr/code-server/issues/1730#issuecomment-659499991

**Comment by code-asher** [comment]
@yozman if you get a chance please try out the steps here and see if they work for you: https://github.com/cdr/code-server/issues/1730#issuecomment-659523851

**Comment by yozman** [comment]
> Interesting, this is different from the errors we've been running into on Termux/Android. [#1730 (comment)](https://github.com/cdr/code-server/issues/1730#issuecomment-659499991)

in my case, I run with 0.0.0.0:8080, it starts successfully and works well first time, but after maybe 10 minutes, it will come up with error on terminal, I killed the process use `ctrl+c` and restart with `code-server`, cannot start with same error

**Comment by yozman** [comment]
> @yozman if you get a chance please try installing code-server using the steps here and see if they work for you: [#1730 (comment)](https://github.com/cdr/code-server/issues/1730#issuecomment-659523851)

follow the step, here is output

```sh
$ code-server
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir ~/.local/share/code-server
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:8090
info    - No authentication
info    - Not serving HTTPS
[IPC Library: File Watcher (nsfw)] Error: dlopen failed: cannot locate symbol "_ZN14InotifyServiceC1ENSt6__ndk110shared_ptrI10EventQueueEENS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" referenced by "/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-nsfw/build/Release/nsfw.node"...
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-nsfw/lib/src/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at t.load (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:16:119)
    at e.load (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:586)
    at i (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:29:259)
    at Object.errorback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:29:383)
    at e.triggerErrorback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:955)
    at /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:659
    at ReadFileContext.callback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:260:13)
```

**Comment by yozman** [comment]
here is my config file

```sh
$ pwd
/data/data/com.termux/files/home
$ cat ~/.config/code-server/config.yaml 
bind-addr: 0.0.0.0:8090
auth: none
password: 7a866d82512a13ca13afdf67
cert: false
disable-telemetry: true
$ 
```

**Comment by yozman** [comment]
I think it's a bug with nsfw native module,
so I opened an issue here
<https://github.com/Axosoft/nsfw/issues/117>
