### ISSUE TITLE
Docker: Restarting container

### ISSUE THREAD

**Issue by martindsouza** [cdr/code-server#2267]
- Web Browser:
- Local OS: MacOS
- Remote OS:
- Remote Architecture:
- `code-server --version`: Docker (latest)

I setup Docker as described here: https://github.com/cdr/code-server/blob/v3.6.2/doc/install.md#docker

```
mkdir -p ~/.config
docker run -it --name code-server -p 127.0.0.1:8080:8080 \
  -v "$HOME/.config:/home/coder/.config" \
  -v "$PWD:/home/coder/project" \
  -u "$(id -u):$(id -g)" \
  -e "DOCKER_USER=$USER" \
  codercom/code-server:latest
```

The initial run works perfectly. I then stop the container using `ctrl+c`. I try to start the container again using: `docker start code-server` and nothing happens.

When I run `docker logs code-server` I get the following: `usermod: user 'coder' does not exist`

**Comment by code-asher** [comment]
Ah interesting our entrypoint script tries to rename the user again but
that'll fail on subsequent runs. We'll need to make sure the user still
exists first. Or maybe there's a way to detect whether this is the first
run.

**Comment by jimmybrancaccio** [comment]
I just wanted to chime in as this started happening to me as well. I'm using v3.7.3 of the Docker image.

**Comment by jasontcole** [comment]
I'm also having this same problem (my server reloaded and the container can't start).

```
$ sudo docker logs code-server
[2020-11-28T15:32:19.797Z] info  code-server 3.7.3 93fb76e4a71b1959ec2a23481ba2611200d714b2
[2020-11-28T15:32:19.801Z] info  Using user-data-dir ~/.local/share/code-server
[2020-11-28T15:32:19.812Z] info  Using config file ~/.config/code-server/config.yaml
[2020-11-28T15:32:19.812Z] info  HTTP server listening on http://0.0.0.0:8080
[2020-11-28T15:32:19.813Z] info    - Authentication is enabled
[2020-11-28T15:32:19.813Z] info      - Using password from ~/.config/code-server/config.yaml
[2020-11-28T15:32:19.813Z] info    - Not serving HTTPS
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[2020-11-28T15:36:09.664Z] error VS Code exited unexpectedly with code 1
usermod: user 'coder' does not exist```

**Comment by woojoo666** [comment]
FYI if anybody is getting this issue on Windows (Docker), it might be because [the fix](https://github.com/cdr/code-server/commit/0cd4f240a3dae9b7c1fd0b77a6824140ce73eda9) references the `$USER` variables, which doesn't exist on windows, I had to map the powershell variable `$env:UserName` to `$USER`, and now it works! Full powershell command below:

```
docker run -it --name code-server -p 127.0.0.1:8080:8080 `
  -v "${HOME}/.code-server-config:/home/coder/.config" `
  -v "${PWD}:/home/coder/project" `
  -e "DOCKER_USER=$env:UserName" `
  -e "USER=$env:UserName" `
  codercom/code-server:latest
```
