### ISSUE TITLE
v.3.6.3 breaks code-server when using install via yarn global add

### ISSUE THREAD

**Issue by csaska** [cdr/code-server#2390]
- Web Browser: Chrome Version 86.0.4240.193 (Official Build) (x86_64)
- Local OS: macOS Big Sur Version 11.0.1
- Remote OS: Red Hat Enterprise Linux 7.5
- Remote Architecture: ppc64le
- `code-server --version`: v3.7.4 though first introduced in v3.7.3

I am trying to deploy code-server to hundreds of Linux on Power machines. Since there is not a standalone release for ppc (and since the standalone release steps do not seem to work on ppc - `yarn vscode` fails to build electron, which why is it even building electron) I am installing code-server via yarn. This has worked fine for v3.7.2.

1. Installed `code-server` on ppc machine
```
$ yarn global add code-server@3.7.4 --exact --force --prefix /usr/local
```

2. Started `code-server`
```
$ code-server --auth none --log debug
[2020-12-02T13:30:03.755Z] info  code-server 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b
[2020-12-02T13:30:03.756Z] info  Using user-data-dir ~/.local/share/code-server
[2020-12-02T13:30:03.766Z] info  Using config file ~/.config/code-server/config.yaml
[2020-12-02T13:30:03.766Z] info  HTTP server listening on http://127.0.0.1:8080
[2020-12-02T13:30:03.766Z] info    - Authentication is disabled
[2020-12-02T13:30:03.766Z] info    - Not serving HTTPS
[2020-12-02T13:30:14.481Z] debug forking vs code...
```

3. Set up SSH port forwarding on my Mac
```
$ ssh -N -L 8080:127.0.0.1:8080 <user>@<remote-host>
```

Connecting through my Mac's Chrome browser immediatley causes the following crash.

![image](https://user-images.githubusercontent.com/22828293/100881084-81e7b580-347b-11eb-8691-b880800d9efe.png)

Contents of `~/.local/share/code-server/coder-logs/code-server-stderr.log`
```
Error: Cannot find module 'applicationinsights'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'applicationinsights',
  neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
}
Error: Cannot find module '@coder/node-browser'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: '@coder/node-browser',
  neededBy: [ 'vs/server/node/channel' ]
}
Error: Cannot find module 'yauzl'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'yauzl',
  neededBy: [ 'vs/base/node/zip' ]
}
Error: Cannot find module 'yazl'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'yazl',
  neededBy: [ 'vs/base/node/zip' ]
}
```

**Comment by code-asher** [comment]
> why is it even building electron

Good question; I'll take a look. We probably need to patch out some default VS Code install script that builds Electron or something.

As for the missing modules, I see this occasionally in our CI. In our case yarn outputs an `ESOCKETTIMEDOUT` and fails to download dependencies. There might be a `yarn-error.log` file that will tell you why the dependencies failed to download in your case.

What I'm not sure about is why the install doesn't immediately fail and exit when this happens. It seems to keep going anyway, resulting in a broken build.

**Comment by code-asher** [comment]
If re-installing doesn't fix it though and it persists with >= 3.7.3 and not <= 3.7.2 then it could definitely be something else. fwiw I just tried with 3.7.4 and all the dependencies downloaded correctly.

**Comment by csaska** [comment]
Wow, yea this time it worked.

Sorry for the noise. I had done this many times before, though in all those times I was using ansible to execute the commands remotely. This time I ssh'd to the machine and did it all myself. Perhaps maybe my install via ansible is using different node/yarn version when it installs than it does when it runs the code-server 

Thanks for all the help! 

My goal here it is to get to a point where I can release standalone RPMs for ppc. If you're interested in releasing them as part of this project, I'd love to help. Otherwise I'll be forking this project and creating CI to release these RPMs through some other means.

**Comment by code-asher** [comment]
To be honest I don't think it's user error, I think yarn/our install script should exit with an error if dependencies fail to download! I'm gonna look into it soon.

I'm down to add ppc RPMs, PRs definitely welcome!

**Comment by DasSkelett** [comment]
So the solution to this problem is "try again until it works", did I understand this correctly?
I am currently trying to install code-server, and while installation works via both yarn and npm, it fails during runtime because of these missing dependencies, just like in this issue:
```
Error: Cannot find module 'applicationinsights'
Error: Cannot find module '@coder/node-browser'
Error: Cannot find module 'yauzl'
Error: Cannot find module 'yazl'
```
