### ISSUE TITLE
code-server-3.7.4: ETIMEDOUT error after install extension

### ISSUE THREAD

**Issue by NamelessAshone** [cdr/code-server#2438]
When I try to install an extension, I get an ETIMEDOUT error. This problem does not occur when I use code-server-3.6.2-linux-amd64.

➜  ~ code-server-3.7.4-linux-amd64/code-server  --install-extension code-server-extensions/AndyCui.vscode-log-viewer-gb2312-0.9.1.vsix --log debug
***** Please use the script in bin/code-server instead!
***** This script will soon be removed!
***** See the release notes at https://github.com/cdr/code-server/releases/tag/v3.4.0
[2020-12-11T02:24:19.301Z] debug forking vs code cli...
[2020-12-11T02:24:19.447Z] debug got message from VS Code {"message":{"type":"ready"}}
debug vscode got message from code-server {"type":"cli"}
Installing extensions...
Extension 'AndyCui.vscode-log-viewer-gb2312-0.9.1.vsix' was successfully installed.
error vscode connect ETIMEDOUT 104.26.1.18:443
error vscode Error: connect ETIMEDOUT 104.26.1.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

**~/.local/share/code-server/logs/  (only cli.log):**
➜  20201211T102419 cat cli.log  
[2020-12-11 10:24:19.456] [cli] [info] main {"_":[],"bind-addr":"127.0.0.1:8080","auth":"none","password":"null","config":"/home/shusx/.config/code-server/config.yaml","install-extension":["code-server-extensions/AndyCui.vscode-log-viewer-gb2312-0.9.1.vsix"],"log":"debug","user-data-dir":"/home/shusx/.local/share/code-server","extensions-dir":"/home/shusx/.local/share/code-server/extensions","verbose":false,"host":"127.0.0.1","port":8080,"proxy-domain":[],"usingEnvPassword":false}
[2020-12-11 10:24:19.474] [cli] [info] Installing the extension: andycui.vscode-log-viewer-gb2312
[2020-12-11 10:24:50.998] [cli] [info] Extracted extension to /home/shusx/.local/share/code-server/extensions/.andycui.vscode-log-viewer-gb2312-0.9.1: andycui.vscode-log-viewer-gb2312
[2020-12-11 10:24:50.999] [cli] [info] Renamed to /home/shusx/.local/share/code-server/extensions/andycui.vscode-log-viewer-gb2312-0.9.1
[2020-12-11 10:24:51.000] [cli] [info] Installation completed. andycui.vscode-log-viewer-gb2312
[2020-12-11 10:24:51.042] [cli] [info] Successfully installed the extension: andycui.vscode-log-viewer-gb2312

- Remote OS:  Debian GNU/Linux 10 (buster)
- Remote Architecture:  x86_64
- `code-server --version`:  3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

**Comment by NamelessAshone** [comment]
Installation of a language package,  got this:

➜  ~ code-server-3.7.4-linux-amd64/code-server --log debug --install-extension code-server-extensions/MS-CEINTL.vscode-language-pack-zh-hans-1.51.2.vsix 
***** Please use the script in bin/code-server instead!
***** This script will soon be removed!
***** See the release notes at https://github.com/cdr/code-server/releases/tag/v3.4.0
[2020-12-11T03:18:14.775Z] debug forking vs code cli...
[2020-12-11T03:18:14.921Z] debug got message from VS Code {"message":{"type":"ready"}}
debug vscode got message from code-server {"type":"cli"}
Installing extensions...
Extension 'MS-CEINTL.vscode-language-pack-zh-hans-1.51.2.vsix' was successfully installed.
error vscode Server returned 500
error vscode Error: Server returned 500
    at Object.t.asJson (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:373:933)
    at j.queryGallery (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:393:695)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async j.query (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:392:642)
    at async j.getExtensions (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:390:251)
    at async /home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:541:148
    at async Promise.all (index 0)
    at async J.getGalleryExtensions (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:541:117)
    at async Promise.all (index 0)
    at async J.installExtensions (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:540:13)
    at async J.run (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:538:205)
    at async /home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:545:678
    at async process.<anonymous> (/home/shusx/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:553:669)

**Comment by NamelessAshone** [comment]
Duplicate of #2355
