### ISSUE TITLE
Failed to install 'golang.go' extension

### ISSUE THREAD

**Issue by sangchul** [cdr/code-server#2573]
- Web Browser: Chrome 87.0.4280.141 (x86_64)
- Local OS: macOS Catalina 10.15.7
- Remote OS: CentOS Linux release 7.4.1708
- Remote Architecture:x86_64
- `code-server --version`:3.8.0

I used golang extension version 0.20.1 and it worked fine and I saw a dialog saying new version of golang extension released (0.20.2) so I tried to upgrade, but vscode says Failed to install 'golang.go'

I checked messages of code-server and it says 

```
(node:1738) UnhandledPromiseRejectionWarning: validating: Unexpected end of data
    at A.downloadInstallableExtension (/home1/irteamsu/packages/code-server-3.8.0-linux-amd64/lib/vscode/out/vs/server/entry.js:523:159)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

And I can't upgrade the extension

Thanks in advance

**Comment by sangchul** [comment]
I've installed golang.Go@0.20.2 from vsix file.
