### ISSUE TITLE
Upgrade to 3.8.0 results in 500 VS Code failed to load

### ISSUE THREAD

**Issue by tomsherrod** [cdr/code-server#2577]
- Web Browser: Chrome 87
- Local OS: macos 10.15.7
- Remote OS: centos 7.8
- Remote Architecture: 
- `code-server --version`: 3.8.0 c4610f7829701aadb045d450013b84491c30580d

Upgraded from 3.5.0 to 3.8.0 via rpm.

![image](https://user-images.githubusercontent.com/7738205/104486022-30ae0400-5599-11eb-8459-ffb4979d2994.png)

systemctl status:
 Main PID: 2972253 (node)
   CGroup: /system.slice/system-code\x2dserver.slice/code-server@id.service
           ├─2972253 /usr/lib/code-server/lib/node /usr/lib/code-server --log debug --disable-telemetry --bind-addr 0.0.0.0:8080 --cert /home/id/ssl/nasa...
           └─2972277 /usr/lib/code-server/lib/node /usr/lib/code-server --log debug --disable-telemetry --bind-addr 0.0.0.0:8080 --cert /home/id/ssl/nasa...

Jan 13 11:58:46 id-server code-server[2972253]: at Object.errorback (/usr/lib/code-server/lib/vscode/out/vs/loader.js:31:313)
Jan 13 11:58:46 id-server code-server[2972253]: at e.triggerErrorback (/usr/lib/code-server/lib/vscode/out/vs/loader.js:14:306)
Jan 13 11:58:46 id-server code-server[2972253]: at /usr/lib/code-server/lib/vscode/out/vs/loader.js:14:10
Jan 13 11:58:46 id-server code-server[2972253]: at ReadFileContext.callback (/usr/lib/code-server/lib/vscode/out/vs/loader.js:18:342)
Jan 13 11:58:46 id-server code-server[2972253]: at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
Jan 13 11:58:46 id-server code-server[2972253]: phase: 'loading',
Jan 13 11:58:46 id-server code-server[2972253]: moduleId: 'proxy-agent',
Jan 13 11:58:46 id-server code-server[2972253]: neededBy: [ 'vs/base/node/proxy_agent' ]
Jan 13 11:58:46 id-server code-server[2972253]: }
Jan 13 11:58:46 id-server code-server[2972253]: [2021-01-13T16:58:46.995Z] error VS Code exited unexpectedly with code 0

From code-server-stderr.log:
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/lib/code-server/lib/vscode/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/code-server/lib/vscode/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/code-server/lib/vscode/node_modules/pac-proxy-agent/dist/agent.js:25:29)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/code-server/lib/vscode/node_modules/pac-proxy-agent/dist/index.js:7:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/code-server/lib/vscode/node_modules/proxy-agent/index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t.load (/usr/lib/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/lib/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/lib/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/lib/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/lib/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/lib/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/lib/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
  phase: 'loading',
  moduleId: 'proxy-agent',
  neededBy: [ 'vs/base/node/proxy_agent' ]
}

**Comment by nhooyr** [comment]
Hmm. Do you have `$HTTP_PROXY` or `$HTTPS_PROXY` set in your environment by any chance? Could also be lowercase versions.

**Comment by tomsherrod** [comment]
Neither of those are set. (upper or lower, nope)

**Comment by gamerhat18** [comment]
I installed code-server via yarn on termux using a non-rooted Android phone. then I forwarded the port 8080 to my entire local network, but it shows "VS Code failed to load. exited unexpectedly with code 0" with a big "500" on top. Before forwarding the port, I tried launching it from my phone's browser and the same thing happened. I am yet to test this out on a rooted device but I doubt that'll change anything. Perhaps I should try to get the Debian ARM version to get working on it, and then I will update this comment.

**Comment by nhooyr** [comment]
@gamerhat18 not sure if this is the correct issue for your comment. There's various other termux issues open. I believe this is unrelated to the termux problems.

**Comment by nhooyr** [comment]
@tomsherrod Can you try `rm -rf ~/.local/share/code-server`?

You may have VS Code's proxy variables set though that shouldn't cause any problems. But give it a shot and let me know.

**Comment by gamerhat18** [comment]
@nhooyr Sorry for posting the wrong issue. I actually searched 500 error for codeserver for the specific version that I had, and this was the search result at top. hence I posted here.

**Comment by nhooyr** [comment]
> @nhooyr Sorry for posting the wrong issue. I actually searched 500 error for codeserver for the specific version that I had, and this was the search result at top. hence I posted here.

All good, just wanted to clarify! :)

**Comment by Nexxkinn** [comment]
Also occured to me on CentOS from 3.7.x to 3.8.0, with the same output from main post.

**Comment by huyinghuan** [comment]
I have the same issue

Server: raspberrypi 4B 8G
OS: Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
Nodejs: v14.15.5
yarn: 1.22.10
npm: 6.14.11
code-server: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b
![QQ20210226-095503](https://user-images.githubusercontent.com/3005433/109243910-bb308700-7818-11eb-812b-1acc1add3aa7.png)

**Comment by LuckyMa5ter** [comment]
I have the same issue hear too, whenever i log in it says vscode exited unexpectedly

**Comment by LuckyMa5ter** [comment]
I am one version 3.9

**Comment by LuckyMa5ter** [comment]
@nhooyr is there any way I can download an older version of this?

**Comment by code-asher** [comment]
I've seen this happen when installing code-server with yarn without the dependencies required to build the native Node modules: https://github.com/cdr/code-server/blob/v3.9.0/docs/npm.md
I've also seen it happen when yarn fails to download dependencies due to network timeouts so it can be helpful to review yarn's output to see if that was the case 

Related: https://github.com/cdr/code-server/issues/2651

**Comment by tomsherrod** [comment]
Gave 3.9.2 a try on the same server, same result. 
npm and yarn appeared to be installed. I followed the instructions and both are already installed.

**Comment by jsjoeio** [comment]
Hmm... @tomsherrod do you mind updating this thread using our [bug report template](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=)? Then we can take a look faster and hopefully help you!

**Comment by tomsherrod** [comment]
Finding the version of code-server to be at 3.9.2 now, I created a new ubuntu vm and installed 3.9.2. I thought the upgrade jump would be a long shot, so no worries. Lesson: keep a bit more current.
Thank you for the support and software. I will use the report template for any further issues.

**Comment by jsjoeio** [comment]
No worries at all! Glad that it was as easy as upgrading.

**Comment by songhanpoo** [comment]
i have same error !

`~# export PASSWORD=password | code-server --bind-addr 0.0.0.0:8080
[2021-06-06T11:14:33.544Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
[2021-06-06T11:14:33.561Z] info  Using user-data-dir ~/.local/share/code-server
[2021-06-06T11:14:33.724Z] info  Using config file ~/.config/code-server/config.yaml
[2021-06-06T11:14:33.726Z] info  HTTP server listening on http://0.0.0.0:5194
[2021-06-06T11:14:33.727Z] info    - Authentication is enabled
[2021-06-06T11:14:33.728Z] info      - Using password from $PASSWORD
[2021-06-06T11:14:33.729Z] info    - Not serving HTTPS
Failed login attempt {"remoteAddress":"192.168.0.103","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36","timestamp":1622978082}
Failed login attempt {"remoteAddress":"192.168.0.103","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36","timestamp":1622978087}
[2021-06-06T11:14:57.537Z] error VS Code exited unexpectedly with code 0
[2021-06-06T11:15:06.172Z] error VS Code exited unexpectedly with code 0
^~# code-server --version
3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005`

**Comment by jsjoeio** [comment]
@songhanpoo please open a separate bug report!
