### ISSUE TITLE
First time access get 500 error from 3.8.0 (and 3.8.1)

### ISSUE THREAD

**Issue by silenceleaf** [cdr/code-server#2691]
Web Browser: Any Browser
Local OS:  Windows 10 (actually any OS will see this issue)
Remote OS:  ArchLinux  5.10.13
Remote Architecture: X86_64
code-server --version:  3.8.1 41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5  (from 3.8.0 version this issue is there)

Below is the error log

```
Feb 07 20:43:47 vm2 code-server[8310]: TypeError: Class extends value undefined is not a constructor or null
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.<anonymous> (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/socks-proxy-agent/dist/agent.js:114:44)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.load (internal/modules/cjs/loader.js:985:32)
Feb 07 20:43:47 vm2 code-server[8310]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
Feb 07 20:43:47 vm2 code-server[8310]:     at require (internal/modules/cjs/helpers.js:72:18)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.<anonymous> (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/socks-proxy-agent/dist/index.js:5:33)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.load (internal/modules/cjs/loader.js:985:32)
Feb 07 20:43:47 vm2 code-server[8310]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
Feb 07 20:43:47 vm2 code-server[8310]:     at require (internal/modules/cjs/helpers.js:72:18)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.<anonymous> (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/pac-proxy-agent/dist/agent.js:25:29)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.load (internal/modules/cjs/loader.js:985:32)
Feb 07 20:43:47 vm2 code-server[8310]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
Feb 07 20:43:47 vm2 code-server[8310]:     at require (internal/modules/cjs/helpers.js:72:18)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.<anonymous> (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/pac-proxy-agent/dist/index.js:7:33)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.load (internal/modules/cjs/loader.js:985:32)
Feb 07 20:43:47 vm2 code-server[8310]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
Feb 07 20:43:47 vm2 code-server[8310]:     at require (internal/modules/cjs/helpers.js:72:18)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.<anonymous> (/home/junyan/storage/app/code-server/Code/lib/vscode/node_modules/proxy-agent/index.js:16:21)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.load (internal/modules/cjs/loader.js:985:32)
Feb 07 20:43:47 vm2 code-server[8310]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
Feb 07 20:43:47 vm2 code-server[8310]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
Feb 07 20:43:47 vm2 code-server[8310]:     at require (internal/modules/cjs/helpers.js:72:18)
Feb 07 20:43:47 vm2 code-server[8310]:     at t.load (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:17:960)
Feb 07 20:43:47 vm2 code-server[8310]:     at e.load (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:13:941)
Feb 07 20:43:47 vm2 code-server[8310]:     at o (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:31:189)
Feb 07 20:43:47 vm2 code-server[8310]:     at Object.errorback (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:31:313)
Feb 07 20:43:47 vm2 code-server[8310]:     at e.triggerErrorback (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:14:306)
Feb 07 20:43:47 vm2 code-server[8310]:     at /home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:14:10
Feb 07 20:43:47 vm2 code-server[8310]:     at ReadFileContext.callback (/home/junyan/storage/app/code-server/Code/lib/vscode/out/vs/loader.js:18:342)
Feb 07 20:43:47 vm2 code-server[8310]:     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
Feb 07 20:43:47 vm2 code-server[8310]:   phase: 'loading',
Feb 07 20:43:47 vm2 code-server[8310]:   moduleId: 'proxy-agent',
Feb 07 20:43:47 vm2 code-server[8310]:   neededBy: [ 'vs/base/node/proxy_agent' ]
Feb 07 20:43:47 vm2 code-server[8310]: }
```

**Comment by jsjoeio** [comment]
It looks like you forgot to fill out the issue template! Can you please provide us the following information along with steps to reproduce this issue?

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

**Comment by silenceleaf** [comment]
> It looks like you forgot to fill out the issue template! Can you please provide us the following information along with steps to reproduce this issue?
> 
> * Web Browser:
> * Local OS:
> * Remote OS:
> * Remote Architecture:
> * `code-server --version`:

Sorry, I have added more info there.

**Comment by silenceleaf** [comment]
I think I found the issue. I have an incorrect file system access privilege setting

**Comment by jsjoeio** [comment]
Glad to hear you figured it out! @silenceleaf
