### ISSUE TITLE
Error: Cannot find module 'applicationinsights' after fresh installation

### ISSUE THREAD

**Issue by cgrotz** [cdr/code-server#2707]
Hey,
after a fresh install on my RPI using the `curl -fsSL https://code-server.dev/install.sh | sh` when calling _code-server_ I sadly receive an error when opening code-server in the browser. There was no error message during installation.

- Web Browser: Chrome
- Local OS: OSX
- Remote OS: Rasperry OS
- Remote Architecture: Raspberry PI 4
- `code-server --version`: 3.8.1

Server log output in console:
```
Error: Cannot find module 'applicationinsights'
Require stack:
- /usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at t.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:286:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'applicationinsights',
  neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
}
Error: Cannot find module '@coder/node-browser'
Require stack:
- /usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at t.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:286:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: '@coder/node-browser',
  neededBy: [ 'vs/server/node/channel' ]
}
Error: Cannot find module 'yauzl'
Require stack:
- /usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at t.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:286:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'yauzl',
  neededBy: [ 'vs/base/node/zip' ]
}
Error: Cannot find module 'yazl'
Require stack:
- /usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at t.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:286:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'yazl',
  neededBy: [ 'vs/base/node/zip' ]
}
```

**Comment by cgrotz** [comment]
It helped manually calling npm install for the missing modules from the /usr/lib/node_modules/code-server folder

**Comment by code-asher** [comment]
Might be https://github.com/cdr/code-server/issues/2651

**Comment by jsjoeio** [comment]
I've definitely seen this before. We had this happening in CI the other day.

> It helped manually calling npm install for the missing modules from the /usr/lib/node_modules/code-server folder

Does that mean you're unblocked and it's working? First priority is getting it working for you, second is to fix this so it doesn't happen again.

**Comment by cgrotz** [comment]
Hi, it works for me now. Thanks. I think it could be related to #2651

**Comment by jsjoeio** [comment]
Great! I will close this then. Thanks for following up! When we work on #2651, we'll keep this in mind.

**Comment by cgrotz** [comment]
Sure, maybe it would be worth checking if the dependencies are part of the dependency tree though. Since I had to call npm install <modulename> since npm install would not fetch them.

**Comment by sriveravi** [comment]
> It helped manually calling npm install for the missing modules from the /usr/lib/node_modules/code-server folder

I was having this same issue on Raspberry pi 3b and did this suggestion. It took a few rounds with sudo and --unsafe-perm and also 
>>sudo npm audit fix --force 

at the end to clean up stuff, but it works. 

I don't like it, but it works. 

If it helps in throubleshooting the underlying issue issue,  I believe it has to do with old nodejs. Initially I got lots of warning from npm version and had to remove existing and then update nodejs and npm:

sudo apt remove nodejs npm
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash
sudo apt-get install -y nodejs

This took me about 90% of the way, and then the fix from cgrotz
