### ISSUE TITLE
Extension request: Tailwind Twin IntelliSense

### ISSUE THREAD

**Issue by edda** [cdr/code-server#2733]
- [ ] Extension name: Tailwind Twin IntelliSense
- [ ] Extension GitHub or homepage: https://github.com/lightyen/vscode-tailwindcss-twin

**Comment by rvion** [comment]
Is there a way to manually install it?
I also need this, but it fails to install from vsix:

```
$ code-server --install-extension tailwindcss-intellisense-twin-0.6.2.vsix
Installing extensions...
Unable to install extension 'lightyen.tailwindcss-intellisense-twin' as it is not compatible with VS Code '1.52.1'.
[2021-02-21T07:43:27.145Z] error vscode Failed Installing Extensions: tailwindcss-intellisense-twin-0.6.2.vsix
[2021-02-21T07:43:27.146Z] error vscode Error: Failed Installing Extensions: tailwindcss-intellisense-twin-0.6.2.vsix
    at J.installExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:550:717)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async J.run (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:548:205)
    at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:555:976
    at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:563:768)
```

**Comment by edda** [comment]
Ah, yes, I just checked, they require VSCode 1.53.0 or higher. I guess there's no point offering it on the marketplace before code server uses that version of VSCode...

**Comment by lightyen** [comment]
I changed the requirement to lower version(1.52.1), you can try now.
