### ISSUE TITLE
Uploading large files via drag/drop crashes

### ISSUE THREAD

**Issue by Pugio** [cdr/code-server#2803]
Drag and drop a large file (90MB+) crashes code server with:
```
[2021-03-01T22:14:59.053Z] trace vscode Protocol message {"token":"---","message":"{\"type\":\"connectionType\",\"commit\":\"---\",\"signedData\":\"\",\"desiredConnectionType\":1}"}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:679:5)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:93:12) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'write'
}


[2021-03-01T22:14:59.381Z] error VS Code exited unexpectedly with code 1
[2021-03-01T22:15:05.733Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:206:19)
    at VscodeProvider.<anonymous> (/usr/lib/code-server/out/node/vscode.js:198:30)
    at step (/usr/lib/code-server/out/node/vscode.js:63:23)
    at Object.next (/usr/lib/code-server/out/node/vscode.js:44:53)
    at fulfilled (/usr/lib/code-server/out/node/vscode.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

^^^ Last message repeated multiple times as frontend attempts to reconnect
```

The UI shows the file being uploaded until it reaches the end (e.g. `90.3MB / 90.3MB`) at which point the upload seems to hang for ~20 seconds, and then the entire code server crashes. With one of our users, the resulting uploaded folder was corrupted and unable to be opened (his upload hung at around 80%). He also noted that all other running python processes crashed at the same time (this is running on a JupyterHub install), AND reported this issue when downloading a similarly sized file. The only environment difference is his Local OS (Windows 10).

When I tried to reproduce this, the resulting file was uploaded successfully (in that all the bytes made it to disk), but code-server still crashed. The frontend asked me to `Reload Window` to restart the code-server instance.

- Web Browser: Chrome Evergreen 88.0.4324.182
- Local OS: 10.14.6
- Remote OS: Ubuntu 20.04
- Remote Architecture: x86_64
- `code-server --version`: 3.8.1 41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5

**Comment by jsjoeio** [comment]
Thanks for the detailed report and for the logs @Pugio! We'll see what we can do to fix this.
