### ISSUE TITLE
Error with getLayoutMap logged to Log (Window)

### ISSUE THREAD

**Issue by jawnsy** [cdr/code-server#2930]
## OS/Web Information

- Web Browser: Version 88.0.4324.182 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)
- Local OS: Debian testing, using code-server installed as a Progressive Web Application
- Remote OS: Arch Linux container image, running on Ubuntu host in GKE
- Remote Architecture: Coder Enterprise
- `code-server --version`: 3.9.0-1 06c7e17674bd72c1bb655471a69e2f1a4244b329

## Steps to Reproduce

1. Uninstall all extensions
2. Clear all log window outputs
3. Close and re-open code-server via the PWA

## Expected

No errors should be logged

## Actual

The following error is shown in Log (Window):

```
[2021-03-18 08:40:26.466] [window] [error] Failed to execute 'getLayoutMap' on 'Keyboard': getLayoutMap() must be called from a top-level browsing context.: Error: Failed to execute 'getLayoutMap' on 'Keyboard': getLayoutMap() must be called from a top-level browsing context.
    at k._getBrowserKeyMapping (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4509:573)
    at k._updateKeyboardLayoutAsync (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4507:893)
    at k.onKeyboardLayoutChanged (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4507:807)
    at https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4510:407
[2021-03-18 08:40:26.852] [window] [error] Failed to execute 'lock' on 'Keyboard': lock() must be called from a top-level browsing context.: Error: Failed to execute 'lock' on 'Keyboard': lock() must be called from a top-level browsing context.
    at https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4469:946
    at c.fire (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:99:696)
    at n.setFullscreen (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:104:325)
    at Object.t.setFullscreen (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:104:907)
    at https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:6889:683
    at c (https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:348:987)
    at https://master.cdr.dev/proxy/environments/6025c9f8-e87bac3ae2d5fbc33c87523f/ide/static/06c7e17674bd72c1bb655471a69e2f1a4244b329/opt/coder/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:349:56
```

## Screenshot

![image](https://user-images.githubusercontent.com/52710/111654336-e548e980-87c5-11eb-9979-36f0971453d1.png)

## Notes

This issue can be reproduced in VS Code: Unknown

**Comment by code-asher** [comment]
Ah yeah this happens when code-server is in an iframe. I haven't investigated yet though if it's something that can be worked around. I'm actually not even sure it causes any issues.

**Comment by jawnsy** [comment]
Ah OK, this seems like something we should resolve in the Coder side by avoiding iframing, I'll close this in favor of us removing the iFrame then
