### ISSUE TITLE
After upgrading to 3.9.2 it is not opening in macOS Safari (mobile or desktop) 

### ISSUE THREAD

**Issue by keloin** [cdr/code-server#3070]
See the screenshot. 
Works in Chrome, not in Safari - tried on iPad and laptop - both HTTP and HTTPS.
Latest version of Safari - 14.0.3 (16610.4.3.1.7) - on the latest version of macOS - 11.2.3 (20D91).
Latest version of Safari on iPadOS - 14.4.2.
Reverting to 3.9.1 solves the problem.
<img width="1109" alt="console" src="https://user-images.githubusercontent.com/5483626/113950143-e621d980-97cd-11eb-8cdd-6d69caca9b5b.png">
Thank you!

**Comment by keloin** [comment]
3.9.2 is also not opening in Chrome on iPad. Works in Chrome on laptop.

**Comment by keloin** [comment]
This is what I see in the logs:

```
Apr 07 18:15:49 home-server systemd[1]: Started code-server.
Apr 07 18:15:50 home-server code-server[4401]: [2021-04-08T00:15:50.842Z] info  code-server 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859
Apr 07 18:15:50 home-server code-server[4401]: [2021-04-08T00:15:50.844Z] info  Using user-data-dir ~/.local/share/code-server
Apr 07 18:15:50 home-server code-server[4401]: [2021-04-08T00:15:50.862Z] info  Using config file ~/.config/code-server/config.yaml
Apr 07 18:15:50 home-server code-server[4401]: [2021-04-08T00:15:50.862Z] info  HTTP server listening on http://0.0.0.0:50000
Apr 07 18:15:50 home-server code-server[4401]: [2021-04-08T00:15:50.862Z] info    - Authentication is disabled
Apr 07 18:15:50 home-server code-server[4401]: [2021-04-08T00:15:50.862Z] info    - Not serving HTTPS
Apr 07 18:15:55 home-server code-server[4401]: [2021-04-08T00:15:55.070Z] error vscode is not running Error: vscode is not running
Apr 07 18:15:55 home-server code-server[4401]:     at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:206:19)
Apr 07 18:15:55 home-server code-server[4401]:     at VscodeProvider.<anonymous> (/usr/lib/code-server/out/node/vscode.js:198:30)
Apr 07 18:15:55 home-server code-server[4401]:     at step (/usr/lib/code-server/out/node/vscode.js:63:23)
Apr 07 18:15:55 home-server code-server[4401]:     at Object.next (/usr/lib/code-server/out/node/vscode.js:44:53)
Apr 07 18:15:55 home-server code-server[4401]:     at fulfilled (/usr/lib/code-server/out/node/vscode.js:35:58)
Apr 07 18:15:55 home-server code-server[4401]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Apr 07 18:15:55 home-server code-server[4401]:     at runNextTicks (internal/process/task_queues.js:66:3)
Apr 07 18:15:55 home-server code-server[4401]:     at processImmediate (internal/timers.js:429:9)
Apr 07 18:15:55 home-server code-server[4401]: Error: invalid distance too far back
Apr 07 18:15:55 home-server code-server[4401]:     at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
Apr 07 18:15:55 home-server code-server[4401]:   errno: -3,
Apr 07 18:15:55 home-server code-server[4401]:   code: 'Z_DATA_ERROR'
Apr 07 18:15:55 home-server code-server[4401]: }
Apr 07 18:15:55 home-server code-server[4401]: [2021-04-08T00:15:55.661Z] warn  vscode invalid distance too far back
Apr 07 18:16:05 home-server code-server[4401]: [2021-04-08T00:16:05.534Z] error vscode Handshake timed out {"token":"062c37c9-eef1-497f-8d5f-a4a13341b5ae"}
Apr 07 18:16:05 home-server code-server[4401]: [2021-04-08T00:16:05.820Z] error vscode Handshake timed out {"token":"bdc59601-6535-4de4-8210-64bb72fb8e7a"}
Apr 07 18:16:05 home-server code-server[4401]: [2021-04-08T00:16:05.870Z] error vscode Handshake timed out {"token":"6523f335-70a5-48cd-941f-7051c9757f39"}
Apr 07 18:16:10 home-server code-server[4401]: [2021-04-08T00:16:10.689Z] error vscode Handshake timed out {"token":"da87818f-cb7c-4304-b402-eceeb00a7a81"}
Apr 07 18:16:10 home-server code-server[4401]: [2021-04-08T00:16:10.761Z] error vscode Handshake timed out {"token":"a8a70eee-6434-4045-98ec-4c3cf3a350e0"}
Apr 07 18:16:13 home-server code-server[4401]: [2021-04-08T00:16:13.230Z] error vscode Handshake timed out {"token":"22f6cf4b-b204-4797-a7ed-19764284cbfe"}
Apr 07 18:16:13 home-server code-server[4401]: [2021-04-08T00:16:13.284Z] error vscode Handshake timed out {"token":"a81cb35b-334a-4c93-817e-ae83e3e9ee7f"}
Apr 07 18:16:14 home-server code-server[4401]: [2021-04-08T00:16:14.546Z] error vscode Handshake timed out {"token":"587830af-646e-4df0-b119-fa48e4c99d6a"}
Apr 07 18:16:14 home-server code-server[4401]: [2021-04-08T00:16:14.591Z] error vscode Handshake timed out {"token":"acd29708-296c-4dfc-999f-a84bd044c25d"}
Apr 07 18:16:48 home-server code-server[4401]: Error: invalid distance too far back
Apr 07 18:16:48 home-server code-server[4401]:     at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
Apr 07 18:16:48 home-server code-server[4401]:   errno: -3,
Apr 07 18:16:48 home-server code-server[4401]:   code: 'Z_DATA_ERROR'
Apr 07 18:16:48 home-server code-server[4401]: }
Apr 07 18:16:48 home-server code-server[4401]: [2021-04-08T00:16:48.901Z] warn  vscode invalid distance too far back
Apr 07 18:16:58 home-server code-server[4401]: [2021-04-08T00:16:58.875Z] error vscode Handshake timed out {"token":"9a3beda1-02c4-4473-b6a3-44bbff80bb73"}
Apr 07 18:17:23 home-server code-server[4401]: [2021-04-08T00:17:23.954Z] error vscode Handshake timed out {"token":"d230c402-ef39-44ad-8e28-ef020a6831f3"}
Apr 07 18:17:24 home-server code-server[4401]: [2021-04-08T00:17:24.005Z] error vscode Handshake timed out {"token":"d61c4dde-e2fc-4c91-bca1-e0ec0da95f64"}
Apr 07 18:22:33 home-server systemd[1]: /usr/lib/systemd/system/code-server@.service:6: Failed to parse service type, ignoring: exec
Apr 07 18:22:33 home-server systemd[1]: Stopping code-server...

```

**Comment by nodesocket** [comment]
Related, see https://github.com/cdr/code-server/issues/3004

**Comment by jsjoeio** [comment]
Thanks for reporting. Duplicate #3004 and #3038 

Please see: https://github.com/cdr/code-server/discussions/3038

We're working on getting a fix out soon!
