### ISSUE TITLE
Installation failed on Termux (Android 11)

### ISSUE THREAD

**Issue by xiongnemo** [cdr/code-server#3329]
## OS/Web Information

- Web Browser: None
- Local OS: None
- Remote OS: Termux (Android 11) on Redmi K40 (alioth)
- Remote Architecture: arm64
- `code-server --version`: None

## Steps to Reproduce

It seems platform-related, as I didn't reproduce it in another phone running Android 9.

```bash
yarn global add code-server
```

## Expected

`code-server` be installed normally.

## Actual

Failed after few seconds (before `postinstall.sh` ran)

```
error /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server: Command failed.
Exit code: 127
Command: ./postinstall.sh
Arguments:
Directory: /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server
Output:
/data/data/com.termux/files/usr/bin/sh: 1: ./postinstall.sh: not found
```

## Logs

`npm run postinstall`'s log:

```
> $ cat /data/data/com.termux/files/home/.npm/_logs/2021-05-09T09_49_23_933Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/data/data/com.termux/files/usr/bin/node',
1 verbose cli   '/data/data/com.termux/files/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'postinstall'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose run-script [ 'postinstall' ]
5 info lifecycle code-server@3.9.3~postinstall: code-server@3.9.3
6 verbose lifecycle code-server@3.9.3~postinstall: unsafe-perm in lifecycle true
7 verbose lifecycle code-server@3.9.3~postinstall: PATH: /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/node_modules/.bin:/data/data/com.termux/files/home/.config/yarn/global/node_modules/.bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
8 verbose lifecycle code-server@3.9.3~postinstall: CWD: /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server
9 silly lifecycle code-server@3.9.3~postinstall: Args: [ '-c', './postinstall.sh' ]
10 info lifecycle code-server@3.9.3~postinstall: Failed to exec postinstall script
11 verbose stack Error: code-server@3.9.3 postinstall: `./postinstall.sh`
11 verbose stack spawn ENOENT
11 verbose stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
11 verbose stack     at ChildProcess.emit (events.js:315:20)
11 verbose stack     at maybeClose (internal/child_process.js:1048:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
12 verbose pkgid code-server@3.9.3
13 verbose cwd /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server
14 verbose Linux 4.19.113-perf-gadd6d93db79e
15 verbose argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "run" "postinstall"
16 verbose node v14.15.4
17 verbose npm  v6.14.10
18 error code ELIFECYCLE
19 error syscall spawn
20 error file sh
21 error errno ENOENT
22 error code-server@3.9.3 postinstall: `./postinstall.sh`
22 error spawn ENOENT
23 error Failed at the code-server@3.9.3 postinstall script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Screenshot

![image](https://user-images.githubusercontent.com/38759782/117567637-82057480-b0ef-11eb-8ae6-1e27a3f2eb5c.png)

## Notes

`bash postinstall.sh` "executes" the script.

![image](https://user-images.githubusercontent.com/38759782/117567807-74042380-b0f0-11eb-9ac2-a9ae33bc9922.png)

`/usr/bin/env` does not work on this model, while on the other phone it works.

![image](https://user-images.githubusercontent.com/38759782/117567852-9d24b400-b0f0-11eb-855c-b0d922b425c7.png)

**Comment by jsjoeio** [comment]
Thank you so much for the detailed investigation and the screenshots! 🙌

I have a Pixel 2 but have not seen this error. The `npm_config_user_agent`  and `integer expression expected` seem like a good place to start though.

Here is the [`postinstall.sh` script](https://github.com/cdr/code-server/blob/main/ci/dev/postinstall.sh). 
@code-asher @oxy any ideas on why this could be happening?

**Comment by jsjoeio** [comment]
Glad you figured it out! 🙌
