### ISSUE TITLE
Something wrong with launching Python Debugger in 3.10

### ISSUE THREAD

**Issue by CT702-7** [cdr/code-server#3364]
## OS/Web Information

![图片](https://user-images.githubusercontent.com/75598070/117914672-6203ca00-b316-11eb-92ab-7e7501461a76.png)

## Steps to Reproduce

1. Update code-server from 3.9.3 to 3.10
2. Update Jupyter and python extension to the latest version
3. Run a python file

## Expected

Everything should be as usual.

## Actual

![图片](https://user-images.githubusercontent.com/75598070/117915190-595fc380-b317-11eb-8612-d8d9e289cca5.png)
It said that there is something wrong in my configuration, which works perfectly in 3.9.3.
I found that it could be fixed by degrading the extension of jupyter to 2021.3. In this way, I can run python files corretctly. However, jupyter notebooks cannot be shown correctly in this way, what I get is a blank page. The following section is the log of jupyter.
It seems that the support for python is down in coder-server 3.10.

## Logs
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonFindInterpreter'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'jupyterEnhancedDataViewer'
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py pip list
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py pip list
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-05-12 03:51:56: Jupyter Kernel Spec not found for a local connection
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-05-12 03:52:01: Failed to start the Daemon, StdErr:  Traceback (most recent call last):
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/__main__.py", line 126, in main
    daemon_module = importlib.import_module(args.daemon_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py", line 16, in <module>
    from vscode_datascience_helpers.daemon.daemon_python import (
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 18, in <module>
    from pyls_jsonrpc.dispatchers import MethodDispatcher
ModuleNotFoundError: No module named 'pyls_jsonrpc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/__main__.py", line 137, in <module>
    main()
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/__main__.py", line 133, in main
    raise Exception("Failed to start daemon")
Exception: Failed to start daemon

Error 2021-05-12 03:52:01: Failed to start the Daemon, ProcEndEx [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:01: Failed  to start the Daemon, Ex [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:01: Pinging Daemon Failed, Class name = d, completed in 5005ms, has a falsy return value, Arg 1: {}, Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:01: Failed to create daemon, Class name = d, completed in 5086ms, has a falsy return value, , Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:01: Failed to create the daemon service, defaulting to activated environment [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"02aaa2e2-0231-4c29-bd96-767cc12369d9" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-3320nn7XXl6heJhe.json
cwd: /home/ubuntu/python3/cv
> /usr/bin/python3 ~/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"02aaa2e2-0231-4c29-bd96-767cc12369d9" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-3320nn7XXl6heJhe.json
cwd: /home/ubuntu/python3/cv
Error 2021-05-12 03:52:05: Failed to start the Daemon, StdErr:  Traceback (most recent call last):
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/__main__.py", line 126, in main
    daemon_module = importlib.import_module(args.daemon_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py", line 16, in <module>
    from vscode_datascience_helpers.daemon.daemon_python import (
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 18, in <module>
    from pyls_jsonrpc.dispatchers import MethodDispatcher
ModuleNotFoundError: No module named 'pyls_jsonrpc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/__main__.py", line 137, in <module>
    main()
  File "/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/pythonFiles/vscode_datascience_helpers/daemon/__main__.py", line 133, in main
    raise Exception("Failed to start daemon")
Exception: Failed to start daemon

Error 2021-05-12 03:52:05: Failed to start the Daemon, ProcEndEx [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:05: Failed  to start the Daemon, Ex [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:05: Pinging Daemon Failed, Class name = d, completed in 5003ms, has a falsy return value, Arg 1: {}, Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:05: Failed to create daemon, Class name = d, completed in 5041ms, has a falsy return value, , Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]
Error 2021-05-12 03:52:05: Failed to create the daemon service, defaulting to activated environment [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:32:199033)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)]

## Notes

This issue can be reproduced in VS Code: No

**Comment by oxy** [comment]
This was an issue with the auto-compiled version of the Jupyter extension, most likely: I have manually fixed the version on the extension gallery.

Can you reinstall the latest versions of both `ms-python.python` and `ms-toolsai.jupyter`?

**Comment by CT702-7** [comment]
@oxy 
I have reinstalled those extensions serveral times, but the problem remains.

**Comment by oxy** [comment]
Can you provide logs when you have the latest version of both extensions?

**Comment by jsjoeio** [comment]
FWIW, I tested out the Python extension yesterday and it seemed to be working: https://github.com/cdr/code-server/issues/2675#issuecomment-838985995

**Comment by CT702-7** [comment]
@jsjoeio 
I fully underderstand those operations in your sreemshot at bottom. And yes, in that way everything makes perfect sense. You just code in the editing area and run the file through terminal commands. However, when I press F5 in the editing area to execute the file, I got the following result:
![图片](https://user-images.githubusercontent.com/75598070/118060499-810d6500-b3c5-11eb-922e-ff58d5675c1d.png)
There aren't any details in the output section in code-server, where I believe prints logs. In my pointer of view, it is saying that the configuration file of my python extension is not  correct.
This is launch.json of my python extension:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "console": "integratedTerminal"
        }
    ]
}
I copy those contents directly from vscode, and work perfectly there.
This is wierd because it never happened in the 3.9.3. What's more, when I degrade ms-toolsai.jupyter to 2021.3.0, everything is ok. So maybe it is not something in ms-python.python but ms-toolsai.jupyter cause the result.

**Comment by CT702-7** [comment]
@oxy 
Sorry, I am not following with you. When I encounter this issue, there isn't any information in the output section in code-server, as far as I am concerned, where prints log. The picture above is all I got. If it is inadequate, could you please tell me where shall I find those logs?

**Comment by CT702-7** [comment]
@oxy 
I reinstalled the extension of jupyter and found out something may be involved in this issue.
It seems that something happened during the installation or initialization of ms-toolsai.jupyter.
Hope it will helpful.

`[2021-05-13 13:14:41.344] [exthost] [info] extension host terminating: received terminate message from renderer
[2021-05-13 13:14:42.388] [exthost] [info] exiting with code 0
[2021-05-13 13:14:46.393] [exthost] [info] extension host started
[2021-05-13 13:14:46.496] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter {"startup":false,"extensionId":{"value":"ms-toolsai.jupyter","_lower":"ms-toolsai.jupyter"},"activationEvent":"onCustomEditor:jupyter.notebook.ipynb"}
[2021-05-13 13:14:46.497] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.6.0/out/client/extension
[2021-05-13 13:14:46.500] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-05-13 13:14:46.501] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/debug-auto-launch/dist/extension
[2021-05-13 13:14:46.516] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-05-13 13:14:46.517] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/git/dist/main
**[2021-05-13 13:14:46.681] [exthost] [error] Activating extension ms-toolsai.jupyter failed due to an error:**
[2021-05-13 13:14:46.681] [exthost] [error] Error: Cannot find module '/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.6.0/out/client/extension'
Require stack:
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
	at Function.Module._load (internal/modules/cjs/loader.js:841:27)
	at Function.i._load (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27950)
	at Function.S._load (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24660)
	at Function.a._load (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:58822)
	at Module.require (internal/modules/cjs/loader.js:1025:19)
	at require (internal/modules/cjs/helpers.js:72:18)
	at Function.t [as __$__nodeRequire] (/usr/lib/code-server/lib/vscode/out/vs/loader.js:5:101)
	at u._loadCommonJSModule (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:26069)
	at u._doActivateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:12457)
	at u._activateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:11516)
	at Object.actualActivateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:9174)
	at f._activateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:84988)
	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:84670
	at Array.map (<anonymous>)
	at f._activateExtensions (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:84658)
	at f.activateByEvent (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:82002)
	at u._activateByEvent (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:10074)
	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:19411
	at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by gogobd** [comment]
I just downgraded my cdr code-server docker because jupyter was broken, what works for me is cdr code-server 3.9.3 and https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix

**Comment by jsjoeio** [comment]
> I fully underderstand those operations in your sreemshot at bottom. And yes, in that way everything makes perfect sense. You just code in the editing area and run the file through terminal commands. However, when I press F5 in the editing area to execute the file, I got the following result:

Ah, my apologies. I didn't realize it was specifically with pressing F5 which sounds like it's specifically with the debugging

**Comment by oxy** [comment]
Hey there; I just tested a clean install of 3.10.2 by installing the Python/Jupyter extensions, and it works fine (setting breakpoints, F5 for debug, autocomplete, variable/stack inspection/etc.); I'm closing this for now.
