### ISSUE TITLE
Can't open folder on Explorer panel

### ISSUE THREAD

**Issue by sestegra** [cdr/code-server#3457]
## OS/Web Information

- Web Browser: Chrome (90.0.4430.212 (Official Build) (x86_64)
- Local OS: macOS 11.3.1
- Remote OS: macOS 11.3.1
- Remote Architecture: macOS 11.3.1
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. Launch Chrome and open code-server URL
2. Click on "Explorer" icon to open Explorer panel
3. Click on "Open Folder" button

## Expected

Folder selection should appear.

## Actual

An error occurs on Web console

## Logs

Web console log
```
ERR command 'workbench.action.files.openFileFolder' not found: Error: command 'workbench.action.files.openFileFolder' not found
    at h._tryExecuteCommand (http://127.0.0.1:8080/static/387b12ef4ca404ffd39d84834e1f0776e9e3c005/usr/local/Cellar/code-server/3.10.2/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:1735:3364)
    at http://127.0.0.1:8080/static/387b12ef4ca404ffd39d84834e1f0776e9e3c005/usr/local/Cellar/code-server/3.10.2/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:1735:3245
    at async u.open (http://127.0.0.1:8080/static/387b12ef4ca404ffd39d84834e1f0776e9e3c005/usr/local/Cellar/code-server/3.10.2/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:628:17651)
    at async a.open (http://127.0.0.1:8080/static/387b12ef4ca404ffd39d84834e1f0776e9e3c005/usr/local/Cellar/code-server/3.10.2/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:628:19675)
```

## Screenshot

![Screenshot 2021-05-24 at 15 25 16](https://user-images.githubusercontent.com/109060/119354368-4f897900-bca4-11eb-8586-26427bf1c256.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by sestegra** [comment]
See #2921 explains similar issue on "Open folder" link on Welcome page.

**Comment by jsjoeio** [comment]
Guessing it's the exact same issue as #2921. I was able to reproduce locally (macOS + Chrome). 

Thanks for flagging this @sestegra 🙌

## Screenshot
https://user-images.githubusercontent.com/3806031/119382438-dde70600-bc76-11eb-96ba-9fdfb14e6acd.mov
