### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by oklas** [cdr/code-server#3665]
## OS/Web Information

- Web Browser: not concern (safari/chrome)
- Local OS: not concern (BigSur)
- Remote OS: **FreeBSD** 12.2-RELEASE r366954 GENERIC 
- Remote Architecture: UNIX
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

```
# echo check for bindings available
dev@devel:~ % echo 'console.log(require("bindings"))' | node
[Function: bindings] {
  getFileName: [Function: getFileName],
  getRoot: [Function: getRoot]
}
# code-server
```

Then load code from remote url from browser 

Actually anyway client side applications worked in browser.

## Expected

no errors

## Actual

```
[2021-06-24T17:59:57.059Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
[2021-06-24T17:59:57.064Z] info  Using user-data-dir ~/.local/share/code-server
[2021-06-24T17:59:57.107Z] info  Using config file ~/.config/code-server/config.yaml
[2021-06-24T17:59:57.108Z] info  HTTP server listening on http://xx.xx.xx.xx:8080 
[2021-06-24T17:59:57.108Z] info    - Authentication is disabled 
[2021-06-24T17:59:57.108Z] info    - Not serving HTTPS 
Error: Could not locate the bindings file. Tried:
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/Debug/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/out/Debug/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/Debug/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/out/Release/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/Release/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/default/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/compiled/14.16.1/freebsd/x64/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/addon-build/release/install-root/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/addon-build/debug/install-root/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/addon-build/default/install-root/spdlog.node
 → /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/lib/binding/node-v83-freebsd-x64/spdlog.node
    at bindings (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:101)
    at r.load (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1719)
    at r.load (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10262)
    at l (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10314)
    at Object.errorback (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10626)
    at /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10332
    at r.load (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1736)
    at r.load (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10262)
    at l (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10314)
    at r._loadModule (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10444)
    at r._resolve (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:6:452)
    at r.defineModule (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6145)
    at r._relativeRequire (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6831)
    at n (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:9420)
    at v (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:4531)
    at new Promise (<anonymous>)
    at b (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:4511)
    at C._createSpdLogLogger (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:5444)
    at new C (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:5260)
    at Ae.initializeServices (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:99964)
    at async Ae.initialize (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:96951)
    at async process.<anonymous> (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:103671) {
  tries: [
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/Debug/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/out/Debug/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/Debug/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/out/Release/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/Release/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/default/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/compiled/14.16.1/freebsd/x64/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/addon-build/release/install-root/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/addon-build/debug/install-root/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/addon-build/default/install-root/spdlog.node',
    '/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/lib/binding/node-v83-freebsd-x64/spdlog.node'
  ],
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
```

This issue can be reproduced in VS Code: No

**Comment by oklas** [comment]
possible related #3668

**Comment by jsjoeio** [comment]
This seems like an issue related to when code-server was installed locally.

What version of Node are you using?

You may be able to `cd /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode` and run `npm rebuild` and then try starting code-server again. Not sure if that will fix this though.

**Comment by oklas** [comment]
It was installed as stated in docs under root. Then running under user.

Node version as required is 14 (v14.16.1)
It was installed with `yarn` (v1.22.10) and yarn says `command 'rebuild' not found` (but that command is documented)

Reinstalling with remove `node_modules` and using command `yarn` stops with message that `python` is required. So at this step I switched to use `npm install` (instead of installing python for now)

Reinstall with `npm install` at mentioned folder stops with that:

```
/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/playwright/lib/utils/browserPaths.js:133
    throw new Error('Unsupported platform: ' + process.platform);
    ^

Error: Unsupported platform: freebsd
    at cacheDirectory (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/playwright/lib/utils/browserPaths.js:133:11)
    at /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/playwright/lib/utils/browserPaths.js:139:36
    at Object.<anonymous> (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/playwright/lib/utils/browserPaths.js:140:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/playwright/lib/install/installer.js:25:22)
```

When you specified `/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode` - may be you mean `/stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/` - that dir does not actually contain file `spdlog.node` or any dir like `out` or `build` as enumerated in log list above: `Could not locate the bindings file. Tried:`

How to find a step when `spdlog.node` is creating? Is it in script retrieved by curl or some else?

**Comment by oklas** [comment]
Also as addition to error above after first request from browser one of the server workers starts to take up all the CPU time:

```
root@devel:~ # ps aux | grep node
user    31675 98.9  6.1 255768 61400  1  R+J  19:39   1:12.18 /stor/usr-local/bin/node /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-fork --type=extensionHost
root    31681  0.0  0.2  11332  2236  0  S+J  19:41   0:00.00 grep node
user    31666  0.0  4.4 248664 44848  1  S+J  19:39   0:01.16 node /usr/local/bin/code-server --auth none
user    31667  0.0  4.6 250300 46424  1  S+J  19:39   0:01.38 /stor/usr-local/bin/node /usr/local/bin/code-server --auth none
user    31672  0.0  6.2 267560 62708  1  S+J  19:39   0:03.52 /stor/usr-local/bin/node /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork
user    31673  0.0  3.1 231204 31248  1  S+J  19:39   0:00.34 /stor/usr-local/bin/node /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-fork --type=ptyHost
user    31674  0.0  5.0 254472 50612  1  S+J  19:39   0:01.79 /stor/usr-local/bin/node /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-fork --type=watcherService
```

**Comment by jsjoeio** [comment]
> It was installed with yarn (v1.22.10) so I go to folder you mentioned and yarn says command 'rebuild' not found (however 'rebuild' command is documented)

I don't think it works with `yarn` but I haven't tried. Usually when this happens during local development, `npm rebuild` instead `lib/vscode` solves the problem (it shouldn't matter that you install globally with `yarn`). 

Hmm...I think at this point, you should remove code-server and start from scratch. Can you try that?
1. remove code-server
2. install with `yarn` globally
3. try running and share the logs

There is probably a dependency or two missing in your environment. These are usually [the ones](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) you need.

**Comment by oklas** [comment]
I found a problem 🚀 

The dependency library `spdlog` was somehow not built.

I go to `spdlog` and install (build):

```
# cd /stor/usr-local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog
# yarn
```

and bindings file `build/Release/spdlog.node` appears

I suppose the reason was network error (or some else) that caused installation break. May be I did not notice and just run again setup. But why it does not rebuilt? - possible `yarn` algorithm consider `spdlog` as installed and does not check target files that must be built.

To be sure that it is not a problem of current `code-server` version I remove `code-server` and reinstall using `curl ..| sh` as in docs. And all is also worked.

So this was undefined problem during installation that caused `spdlog` to not build.

**Comment by jsjoeio** [comment]
Ahh...interesting 🤔 I don't think I've seen that before. Nice debugging! Glad you were able to find the root cause and get things work. Thanks for following up with the details!
