### ISSUE TITLE
Error: vscode is not running

### ISSUE THREAD

**Issue by oklas** [cdr/code-server#3668]
## OS/Web Information

- Web Browser: not concern (safari/chrome)
- Local OS: not concern (BigSur)
- Remote OS: **FreeBSD** 12.2-RELEASE r366954 GENERIC 
- Remote Architecture: UNIX
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

```
# code-server
```

**Load** code from browser from client side does **not necessary**.

Only **start code server** on remote server is required.  

This error appears not each time but **periodically**. Seems about each odd or even start approximately.

Actually anyway client side applications worked in browser.

## Expected

no errors

## Actual

```
[2021-06-24T19:31:56.345Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
[2021-06-24T19:31:56.349Z] info  Using user-data-dir ~/.local/share/code-server
[2021-06-24T19:31:56.385Z] info  Using config file ~/.config/code-server/config.yaml
[2021-06-24T19:31:56.386Z] info  HTTP server listening on http://xx.xx.xx.xx:8080 
[2021-06-24T19:31:56.386Z] info    - Authentication is disabled 
[2021-06-24T19:31:56.386Z] info    - Not serving HTTPS 
[2021-06-24T19:31:57.583Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:206:19)
    at VscodeProvider.<anonymous> (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:198:30)
    at step (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:63:23)
    at Object.next (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:44:53)
    at fulfilled (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-06-24T19:31:58.287Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:206:19)
    at VscodeProvider.<anonymous> (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:198:30)
    at step (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:63:23)
    at Object.next (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:44:53)
    at fulfilled (/stor/usr-local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This issue can be reproduced in VS Code: No

**Comment by oklas** [comment]
possible related #3668

**Comment by jsjoeio** [comment]
This can happen if you have another browser window or tab where you were previously accessing your code-server instance. Is that the case here?

**Comment by oklas** [comment]
It is possible that it is actually was a reason. To be sure need to see some time. I close for now.
