### ISSUE TITLE
Problems with GLIBC_2.28 on raspbian

### ISSUE THREAD

**Issue by Hugovidafe** [cdr/code-server#3705]
## OS/Web Information

- Web Browser: Any
- Local OS: Any
- Remote OS: Raspberry Pi OS (Raspbian)
- Remote Architecture: armhf
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. Install code-server with npm
2. Configure Caddy
3. Open the web browser with the domain where is hosted

## Expected

I expected me that I could open the terminal and others.

## Actual

I got an error showing me that there was not an already installed dependence.

## Logs

```
[2021-07-01T18:59:31.763Z] debug vscode got message from code-server {"type":"init"}
Error: /snap/core/current/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at bindings (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at t (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:101)
    at r.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1719)
    at r.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10262)
    at l (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10626)
    at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10332
    at r.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1736)
    at r.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10262)
    at l (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10444)
    at r._resolve (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:6:452)
    at r.defineModule (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6831)
    at n (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:5:9420)
    at v (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:4531)
    at new Promise (<anonymous>)
    at b (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:4511)
    at C._createSpdLogLogger (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:5444)
    at new C (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:24:5260)
    at Ae.initializeServices (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:99964)
    at async Ae.initialize (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:96951)
    at async process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:103671) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
```

## Screenshot

![image](https://user-images.githubusercontent.com/69076992/124176812-b40fd300-daaf-11eb-8dbf-c7f7d4cbe933.png)

![2021-07-01-211137_1680x1050_scrot](https://user-images.githubusercontent.com/69076992/124177778-f84fa300-dab0-11eb-8426-7bb92199f141.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thanks for the detailed report @Hugovidafe! I wish I had some insight into how to fix this 🤔 @code-asher or @oxy might (they're more knowledgeable in this area)

**Comment by Hugovidafe** [comment]
Any progress? Can I remove the code-server?

**Comment by RobertCNelson** [comment]
@Hugovidafe glibc 2.28 shipped with Buster, are you running Raspbian Stretch? (which shipped with 2.24)

https://packages.debian.org/source/stretch/glibc

Regards,

**Comment by jsjoeio** [comment]
Sorry all! Both code-asher and oxy are either on vacation or on a light week so it's mostly me fielding these. 

^Seems like an answer to @RobertCNelson's question might help though 🤞

**Comment by Hugovidafe** [comment]
> @Hugovidafe glibc 2.28 shipped with Buster, are you running Raspbian Stretch? (which shipped with 2.24)
> 
> https://packages.debian.org/source/stretch/glibc
> 
> Regards,

I'm using the latest version of Raspberry Pi OS, is there any way to know if it's buster, stretch or another?

**Comment by RobertCNelson** [comment]
Just run this..
```
lsb_release -a
```

If it is buster, then i guess the next question, is it related to a snap dependency?
```
[2021-07-01T18:59:31.763Z] debug vscode got message from code-server {"type":"init"}
Error: /snap/core/current/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)
```

Regards,

**Comment by Hugovidafe** [comment]
![image](https://user-images.githubusercontent.com/69076992/124963017-98607b80-e01f-11eb-94f3-09a7691fbed5.png)
![image](https://user-images.githubusercontent.com/69076992/124963135-baf29480-e01f-11eb-93c4-18feb8c13f2d.png)

**Comment by jsjoeio** [comment]
@RobertCNelson any other suggestions?
