### ISSUE TITLE
Language extension not works.

### ISSUE THREAD

**Issue by LollipopKit** [cdr/code-server#3765]
## OS/Web Information

- Web Browser: Edge
- Local OS: Windows
- Remote OS: Debian
- Remote Architecture: amd64
- `code-server --version`: 3.10.2

## Steps to Reproduce

1. Install Simplified Chinese Extension
2. Then log:
![install log](https://user-images.githubusercontent.com/10864310/125199018-f1861480-e296-11eb-93cb-d98576725f5e.png)
3. Relaunch with cmd `code-server`

## Expected
Display in zh-cn

## Actual
Logout:
![log after install](https://user-images.githubusercontent.com/10864310/125198953-b257c380-e296-11eb-9c3d-2b556137685e.png)

Can't launch in first serveral retries.  
After recovering from launching problem, still display in en.

## Logs

```shell
[2021-07-11T14:03:06.119Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
[2021-07-11T14:03:06.120Z] info  Using user-data-dir ~/.local/share/code-server
[2021-07-11T14:03:06.129Z] info  Using config file ~/.config/code-server/config.yaml
[2021-07-11T14:03:06.129Z] info  HTTP server listening on http://127.0.0.1:8080 
[2021-07-11T14:03:06.129Z] info    - Authentication is enabled
[2021-07-11T14:03:06.129Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-07-11T14:03:06.129Z] info    - Not serving HTTPS 
[2021-07-11T14:03:06.423Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:206:19)
    at VscodeProvider.<anonymous> (/usr/lib/code-server/out/node/vscode.js:198:30)
    at step (/usr/lib/code-server/out/node/vscode.js:63:23)
    at Object.next (/usr/lib/code-server/out/node/vscode.js:44:53)
    at fulfilled (/usr/lib/code-server/out/node/vscode.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-07-11T14:03:06.425Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:206:19)
    at VscodeProvider.<anonymous> (/usr/lib/code-server/out/node/vscode.js:198:30)
    at step (/usr/lib/code-server/out/node/vscode.js:63:23)
    at Object.next (/usr/lib/code-server/out/node/vscode.js:44:53)
    at fulfilled (/usr/lib/code-server/out/node/vscode.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Screenshot

![display in en, not zh-cn](https://user-images.githubusercontent.com/10864310/125198972-c4396680-e296-11eb-8237-22d47bd22115.png)

![this extension works properly in vscode](https://user-images.githubusercontent.com/10864310/125198723-b59e7f80-e295-11eb-8152-28a9ad624ac4.png)

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Hmm...I just tried to reproduce locally and couldn't 🤔

Nothing looks unusual about the logs either. Do you mind trying a different language like Spanish and letting me know if it works?

## Video

https://user-images.githubusercontent.com/3806031/125332307-c97dcc00-e2fd-11eb-8246-1a6098b785cf.mov

**Comment by LollipopKit** [comment]
Thanks for your reply.  
Hmm...It works fine after retrying...  
I can't figure out why the problem occurred before.   
https://user-images.githubusercontent.com/10864310/125367195-4a929d00-e3aa-11eb-9437-ea9525b1c747.mov

**Comment by jsjoeio** [comment]
Maybe just a blip? Glad it's working!
