### ISSUE TITLE
Can't install Vim extension

### ISSUE THREAD

**Issue by wanningfe** [cdr/code-server#3945]
## OS/Web Information

- Web Browser: Safari
- Local OS: macOS
- Remote OS: Arch Linux
- Remote Architecture: X86 64
- `code-server --version`:  3.11.1

## Steps to Reproduce

1. Search Vim on Code server extension store
2. Vim extension saids it is not a web extension, so there is no remote install button but a 'local install' button
3. Click 'local Install'(I am not sure the spell because my coder just can't switch language, maybe another bug?)
4. Vim can't install because it seems that coder can only install web extension (See log on my screenshot)

## Expected

Vim extention installed successfully and runs well

## Actual
Vim will not install

## Logs

[2021-08-10 18:08:00.572] [window] [error] Cannot install 'Vim' because this extension is not a web extension.: https://files.zhenghuowang.com:9999/static/c680aae973d83583e4a73dc0c422f44021f0140e/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1798:4563433
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]

## Screenshot

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/25128272/128849016-7dba77e6-ca6f-4282-8854-43062386a37c.png">

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
I see the same error:

```javascript
[2021-08-10 11:55:28.302] [window] [error] Cannot install 'Vim' because this extension is not a web extension.: Error: Cannot install 'Vim' because this extension is not a web extension.
    at E.installFromGallery (http://localhost:8080/static/acb5de66b71a3f8f1cc065df4633ecd3f9788d46/Users/jp/.config/yarn/global/node_modules/@jsjoeio/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1798:27286)
    at async Promise.all (index 0)
    at async Object.G [as settled] (http://localhost:8080/static/acb5de66b71a3f8f1cc065df4633ecd3f9788d46/Users/jp/.config/yarn/global/node_modules/@jsjoeio/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:68:20843)
```

As a temporary workaround, you can use `v1.18.9` which I know works. 

It seems like this is not limited to code-server according to this issue: https://github.com/VSCodeVim/Vim/issues/6826

I'm going to close since we can't fix ourselves, but at least you can subscribe to that issue and see when it gets resolved.

**Comment by ochen1** [comment]
Installing the extension for code-server via CLI worked for me.

https://github.com/VSCodeVim/Vim/issues/6826#issuecomment-945058969

**Comment by jsjoeio** [comment]
Hooray! Can we close this out?
