### ISSUE TITLE
Terminal result can't be seen, but have response.

### ISSUE THREAD

**Issue by LollipopKit** [cdr/code-server#4260]
## OS/Web Information

- Web Browser: safari 15.0
- Local OS: macOS big sur 11.6
- Remote OS: Debian 10.2
- Remote Architecture: amd64
- `code-server --version`: 3.12.0

## Steps to Reproduce

1.open terminal in code-server web page.
2.type any cmd.

## Expected
Show cmd result.

## Actual
Terminal responded, but can't be seen.Seem like transparent font color.

## Logs
```shell
➜  ~ code-server --log debug
[2021-09-28T09:11:51.597Z] info  code-server 3.12.0 b37ff28a0a582aee84a8f961755d0cb40a4081db
[2021-09-28T09:11:51.598Z] info  Using user-data-dir ~/.local/share/code-server
[2021-09-28T09:11:51.615Z] info  Using config file ~/.config/code-server/config.yaml
[2021-09-28T09:11:51.615Z] info  HTTP server listening on http://127.0.0.1:8080 
[2021-09-28T09:11:51.615Z] info    - Authentication is enabled
[2021-09-28T09:11:51.615Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-09-28T09:11:51.615Z] info    - Not serving HTTPS 
[2021-09-28T09:11:54.765Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-28T09:11:54.767Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-28T09:11:55.180Z] debug forking vs code...
[2021-09-28T09:11:55.463Z] debug setting up vs code...
[2021-09-28T09:11:55.467Z] debug vscode got message from code-server {"type":"init"}
[2021-09-28T09:11:56.130Z] debug vscode got message from code-server {"type":"socket"}
[2021-09-28T09:11:56.132Z] debug protocol Initiating handshake... {"token":"008ffa59-ba67-45af-ac75-7a5b12eb3a9a"}
[2021-09-28T09:11:56.179Z] debug protocol Handshake completed {"token":"008ffa59-ba67-45af-ac75-7a5b12eb3a9a"}
[2021-09-28T09:11:56.180Z] debug management Connecting... {"token":"008ffa59-ba67-45af-ac75-7a5b12eb3a9a"}
[2021-09-28T09:11:56.180Z] debug vscode 1 active management connection(s)
[2021-09-28T09:11:56.598Z] debug got latest version {"latest":"3.12.0"}
[2021-09-28T09:11:56.598Z] debug comparing versions {"current":"3.12.0","latest":"3.12.0"}
[2021-09-28T09:11:56.697Z] debug vscode got message from code-server {"type":"socket"}
[2021-09-28T09:11:56.698Z] debug protocol Initiating handshake... {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:56.751Z] debug protocol Handshake completed {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:56.752Z] debug exthost Connecting... {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:56.752Z] debug exthost Getting NLS configuration... {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:56.752Z] debug vscode 1 active exthost connection(s)
[2021-09-28T09:11:56.752Z] debug exthost Spawning extension host... {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:56.756Z] debug exthost Waiting for handshake... {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:57.275Z] debug exthost Handshake completed {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:11:57.275Z] debug exthost Sending socket {"token":"7f29da65-23a4-431b-878a-0a064eb99e19"}
[2021-09-28T09:12:54.753Z] debug 2 active connections
```

#### Safari
https://user-images.githubusercontent.com/10864310/135058885-8c923626-a4b0-4892-bf98-9f4bb0a24304.mov
#### Chrome
![image](https://user-images.githubusercontent.com/10864310/135060532-b828f53a-79c2-4bbb-bbfa-a791ce2205de.png)

## Notes
Although Safari will have problems, Chrome will not, but I still hope this problem can be fixed.
This issue can be reproduced in VS Code: Yes

Thank you for your effort.

**Comment by LollipopKit** [comment]
Although Safari will have problems, Chrome will not, but I still hope this problem can be fixed.
Thank you for your effort.

**Comment by bpmct** [comment]
Thanks for reporting! This is a known issue which can be solved by turning of GPU acceleration for the terminal in settings. See #3824 for details.

Let us know if you run into any more issues running on iPad, we’re hoping to fix most of these soon. We also have a [page dedicated to the iPad](https://coder.com/docs/code-server/v3.12.0/ipad) where we include guides and known issues.
