### ISSUE TITLE
Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)

### ISSUE THREAD

**Issue by JulesGM** [cdr/code-server#4271]
## OS/Web Information

- Web Browser: Chrome Version 93.0.4577.82 (Official Build) (x86_64)
- Local OS: MacOS 11.5.2
- Remote OS:  Operating System: Ubuntu 18.04.5 LTS, Kernel: Linux 5.4.0-62-generic
- Remote Architecture: x86_64
- `code-server --version`: 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2

## Steps to Reproduce

1. Unpack the latest release with `tar -xf code-server-3.12.0-linux-amd64.tar.gz`
2. Edit the config.yml to work with 0.0.0.0 and port 8889
3. Run the server with `cd ~/code_server/code-server-3.12.0-linux-amd64/bin ; ./code-server.sh`
3. Connect through the browser, enter the password.
4. Click on the extensions tab, search for python install the Python `ms-python` extension.
5. CMD + SHIFT + P: Jupyter .. no result.
6. Restart the server by closing the browser window and ctrl-C the script, then ./code-server.sh. 
7. CMD + SHIFT + P: Jupyter create blank file: get popup that says "Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)" with a red X with a circle and a blue OK button.

or 

7.  Try to open an `ipynb` file. SHIFT-ENTER a cell. No kernel, asks to `search marketplace..`. It suggests `Jupyter`. Click on it. It's already installed.

## Expected

I maybe install the Python and or jupyter extension, open an `ipynb` script, it works / I can create blank ipynb files.

## Actual

 CMD + SHIFT + P: Jupyter create blank file: get popup that says "Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)" with a red X with a circle and a blue OK button.

or 

 Try to open an `ipynb` file. SHIFT-ENTER a cell. No kernel, asks to `search marketplace..`. It suggests `Jupyter`. Click on it. It's already installed.

## Logs

These are the logs from Log (remote extension host). Seems related.

```
[2021-09-29 16:32:20.063] [exthost] [info] extension host started
[2021-09-29 16:32:20.066] [exthost] [error] Error: listen EACCES: permission denied /run/user/1471600291/vscode-ipc-2cc268e4-5783-483c-8188-f66fd95f7cbc.sock
    at Server.setupListenHandle [as _listen2] (net.js:1303:21)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1465:5)
    at c.setup (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:22027)
    at new T (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:21796)
    at new c (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:24275)
    at n._createInstance (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:1374)
    at n.createInstance (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:793)
    at p._beforeAlmostReadyToRunExtensions (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25336)
    at p.initialize (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9522)
    at new E (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:102:10059)
    at g (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:32416)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-09-29 16:32:20.067] [exthost] [error] Error: EEXIST: file already exists, open '/home/mila/g/gagnonju/.local/share/code-server/User/workspaceStorage/-6114915c/vscode.lock'
[2021-09-29 16:32:20.083] [exthost] [info] Lock '/home/mila/g/gagnonju/.local/share/code-server/User/workspaceStorage/-6114915c/vscode.lock': Could not acquire lock, checking if the file is stale.
[2021-09-29 16:32:20.101] [exthost] [info] Lock '/home/mila/g/gagnonju/.local/share/code-server/User/workspaceStorage/-6114915c/vscode.lock': The pid 20713 appears to be gone.
[2021-09-29 16:32:20.101] [exthost] [info] Lock '/home/mila/g/gagnonju/.local/share/code-server/User/workspaceStorage/-6114915c/vscode.lock': Deleting a stale lock.
[2021-09-29 16:32:20.106] [exthost] [info] Lock '/home/mila/g/gagnonju/.local/share/code-server/User/workspaceStorage/-6114915c/vscode.lock': Lock acquired.
[2021-09-29 16:32:20.170] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb {"startup":false,"activationEvent":"onNotebook:jupyter-notebook}","extensionId":{"value":"vscode.ipynb","_lower":"vscode.ipynb"}}
[2021-09-29 16:32:20.170] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/ipynb/dist/ipynbMain.js
[2021-09-29 16:32:20.198] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-09-29 16:32:20.199] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/debug-auto-launch/dist/extension
[2021-09-29 16:32:20.216] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-09-29 16:32:20.216] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/git/dist/main
[2021-09-29 16:32:20.315] [exthost] [info] ExtensionService#_doActivateExtension oderwat.indent-rainbow {"startup":true,"extensionId":{"value":"oderwat.indent-rainbow","_lower":"oderwat.indent-rainbow"},"activationEvent":"*"}
[2021-09-29 16:32:20.316] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/.local/share/code-server/extensions/oderwat.indent-rainbow-7.4.0/out/extension
[2021-09-29 16:32:20.332] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":true,"extensionId":{"value":"ms-python.python","_lower":"ms-python.python"},"activationEvent":"workspaceContains:requirements.txt"}
[2021-09-29 16:32:20.332] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/.local/share/code-server/extensions/ms-python.python-2021.9.1246542782/out/client/extension
[2021-09-29 16:32:20.748] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-09-29 16:32:20.748] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/github/dist/extension.js
[2021-09-29 16:32:21.025] [exthost] [info] Extension 'ms-python.python' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
[2021-09-29 16:32:21.057] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-09-29 16:32:21.057] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/emmet/dist/node/emmetNodeMain
[2021-09-29 16:32:21.088] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-09-29 16:32:21.089] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/merge-conflict/dist/mergeConflictMain
[2021-09-29 16:32:21.102] [exthost] [info] eager extensions activated
[2021-09-29 16:32:21.218] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-09-29 16:32:21.219] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/ms-vscode.js-debug/src/extension.js
[2021-09-29 16:32:21.555] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter {"startup":false,"extensionId":{"value":"ms-toolsai.jupyter","_lower":"ms-toolsai.jupyter"},"activationEvent":"onNotebook:jupyter-notebook"}
[2021-09-29 16:32:21.555] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/mila/g/gagnonju/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.8.12/out/client/extension
[2021-09-29 16:32:21.575] [exthost] [error] Activating extension ms-toolsai.jupyter failed due to an error:
[2021-09-29 16:32:21.576] [exthost] [error] Error: Cannot find module '/home/mila/g/gagnonju/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.8.12/out/client/extension'
Require stack:
- /home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/loader.js
- /home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/bootstrap-amd.js
- /home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
	at Function.Module._load (internal/modules/cjs/loader.js:745:27)
	at Function.u._load (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28329)
	at Function.E._load (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:24906)
	at Function.o._load (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:59872)
	at Module.require (internal/modules/cjs/loader.js:961:19)
	at Module.require (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/extensions/git/dist/main.js:2:515806)
	at require (internal/modules/cjs/helpers.js:92:18)
	at Function.t [as __$__nodeRequire] (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/loader.js:5:101)
	at p._loadCommonJSModule (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26315)
	at p._doActivateExtension (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12594)
	at p._activateExtension (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11695)
	at Object.actualActivateExtension (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9236)
	at c._activateExtension (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:87973)
	at /home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:87655
	at Array.map (<anonymous>)
	at c._activateExtensions (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:87643)
	at c.activateByEvent (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:84977)
	at p._activateByEvent (/home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10175)
	at /home/mila/g/gagnonju/code_server/code-server-3.12.0-linux-amd64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:19973
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-09-29 16:32:22.628] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1207
```

**Comment by jsjoeio** [comment]
Curious why you're installing that way instead of following [the docs](https://coder.com/docs/code-server/v3.12.0/install#debian-ubuntu)?

> Click on the extensions tab, search for python install the Python ms-python extension.

Unless you're overriding the environment variables somewhere, installing these extensions from the current marketplace will not work 😢 We're working on transitioning to the [Open VSX marketplace](https://open-vsx.org/).

Can you please install both Python and Jupyter from there and see if you're still getting this issue? 

If you prefer the command line, you can also [follow the docs](https://coder.com/docs/code-server/v3.12.0/FAQ#how-do-i-install-an-extension-manually):

```shell
SERVICE_URL=https://open-vsx.org/vscode/gallery ITEM_URL=https://open-vsx.org/vscode/item code-server --install-extension <extension id>
```

**Comment by JulesGM** [comment]
I'm following https://coder.com/docs/code-server/v3.12.0/install#standalone-releases
I don't have sudo access, and I had similar errors with the `npm` method

**Comment by JulesGM** [comment]
Didn't see the part about the extensions. Thanks. Was it easily visible in the installation docs? I feel like it should be a pretty common issue

**Comment by jsjoeio** [comment]
> I don't have sudo access, and I had similar errors with the npm method

Ah, got it. Makes sense.

> Didn't see the part about the extensions. Thanks.

Sure! Let me know if that works.

**Comment by JulesGM** [comment]
It works! Thanks a lot for your help.
May I suggest that maybe this extension marketplace stuff should be made more obvious? Anyways thanks a lot again.

**Comment by jsjoeio** [comment]
> May I suggest that maybe this extension marketplace stuff should be made more obvious? Anyways thanks a lot again.

Sure! We actually added this earlier in 2020 but I'm sure a lot of folks (myself included) dismiss this without reading it.

![image](https://user-images.githubusercontent.com/3806031/135360880-950a1162-a829-4057-a8f8-61c28c390942.png)

If you have any better ideas, let us know! (eventually though we'll use Open VSX by default so this won't be a problem)

**Comment by JulesGM** [comment]
Well I would put something similar to your great comment https://github.com/cdr/code-server/issues/4271#issuecomment-930582008 in the docs at https://coder.com/docs/code-server/v3.12.0/install , as every single coder will want to install the extension for their language afaik

**Comment by JulesGM** [comment]
maybe not every single one but a lot

**Comment by caioolivv** [comment]
I have encountered the same exact error, even though I followed the guide. What's more strange, depeding on the machine I'm accessing code-server from, the editor is not even able to parse notebooks.

**Comment by jsjoeio** [comment]
@JulesGM awesome! I opened an issue for us to tackle there here: https://github.com/cdr/code-server/issues/4282

> I have encountered the same exact error, even though I followed the guide. What's more strange, depeding on the machine I'm accessing code-server from, the editor is not even able to parse notebooks.

Hmm...not sure what that is. If it's a bug, feel free to open a separate bug report and we can look into it.

**Comment by JulesGM** [comment]
Cool @jsjoeio !
@caioolivv I had to delete my previous install where I had used the regular extension store and start a fresh one.
