### ISSUE TITLE
Cannot find module 'js-yaml'

### ISSUE THREAD

**Issue by ssebastianoo** [cdr/code-server#4424]
## OS/Web Information

- Web Browser:
- Local OS: `Ubuntu Server 21.10`
- Remote OS:
- Remote 
- Architecture: `aarch64`
- `code-server --version`: _the same error happens if I try this command_

## Steps to Reproduce

1. install code-server
2. run code-server

## Expected

It should start code-server

## Actual

```sh
ubuntu@ubuntu:~$ code-server
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'js-yaml'
Require stack:
- /usr/local/lib/node_modules/code-server/out/node/cli.js
- /usr/local/lib/node_modules/code-server/out/node/entry.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-server/out/node/cli.js:28:35)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/code-server/out/node/cli.js',
    '/usr/local/lib/node_modules/code-server/out/node/entry.js'
  ]
}

```
## Notes
I already tried `sudo npm i -g js-yaml`

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
I have never seen this before 🤔 Can you install again and then paste the install logs here?

**Comment by ssebastianoo** [comment]
> I have never seen this before 🤔 Can you install again and then paste the install logs here?

I reinstalled node and it solved. everything

**Comment by jsjoeio** [comment]
Oh weird! That was easy 😂 Closing this.
