### ISSUE TITLE
Latest version of extensions unavailable + extension details page blank

### ISSUE THREAD

**Issue by pheetr** [cdr/code-server#4592]
## OS/Web Information

- Web Browser: FF 94.0.2 (64-bit), Chrome 96.0.4664.45 (64-bit)
- Local OS: Win10
- Remote OS: Ubuntu 20.04.3 LTS
- Remote Architecture: Docker 20.10.10
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. Deploy official container as outlined [here](https://coder.com/docs/code-server/latest/install#docker)
2. Log into code-server
3. Browse extensions

## Expected

Extensions should show up with their latest versions and with details displayed.
Taking the example of Python, the version provided is one version behind what is visible on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=ms-python.python). 
For ESPHome it is a much older version: v0.1.0 vs. v0.22.0 on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=ESPHome.esphome-vscode).

## Actual

Extensions show older versions and details page is blank.

## Logs

Docker container logs:

[2021-12-08T14:39:39.017Z] debug parsed command line {"args":{"_":["."],"bind-addr":"0.0.0.0:8080"}},
[2021-12-08T14:39:39.051Z] debug parsed command line {"args":{"_":[],"bind-addr":"127.0.0.1:8080","auth":"password"}},
[2021-12-08T14:39:39.057Z] debug parent:33 spawned inner process 52,
[2021-12-08T14:39:39.526Z] info  code-server 3.12.0 2661a690ac228872e8d1dc28ab6d33e8afc30add,
[2021-12-08T14:39:39.527Z] info  Using user-data-dir ~/.local/share/code-server,
[2021-12-08T14:39:39.550Z] info  Using config file ~/.config/code-server/config.yaml,
[2021-12-08T14:39:39.552Z] info  HTTP server listening on http://0.0.0.0:8080 ,
[2021-12-08T14:39:39.552Z] info    - Authentication is enabled,
[2021-12-08T14:39:39.552Z] info      - Using password from ~/.config/code-server/config.yaml,
[2021-12-08T14:39:39.552Z] info    - Not serving HTTPS ,
[2021-12-08T14:39:39.826Z] error vscode is not running Error: vscode is not running,
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19),
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14),
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5,
[2021-12-08T14:39:42.372Z] error vscode is not running Error: vscode is not running,
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19),
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14),
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5,
[2021-12-08T14:39:59.856Z] error vscode is not running Error: vscode is not running,
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19),
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14),
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5,
[2021-12-08T14:39:59.941Z] debug forking vs code...,
[2021-12-08T14:40:00.551Z] debug setting up vs code...,
[2021-12-08T14:40:00.555Z] debug vscode got message from code-server {"type":"init"},
[2021-12-08T14:40:01.458Z] debug vscode got message from code-server {"type":"socket"},
[2021-12-08T14:40:01.460Z] debug protocol Initiating handshake... {"token":"e2e2c0ff-ad7e-4d4f-a9af-260234cff891"},
[2021-12-08T14:40:01.467Z] debug protocol Handshake completed {"token":"e2e2c0ff-ad7e-4d4f-a9af-260234cff891"},
[2021-12-08T14:40:01.468Z] debug management Connecting... {"token":"e2e2c0ff-ad7e-4d4f-a9af-260234cff891"},
[2021-12-08T14:40:01.468Z] debug vscode 1 active management connection(s),
[2021-12-08T14:40:01.700Z] debug Making request {"uri":"https://api.github.com/repos/cdr/code-server/releases/latest"},
[2021-12-08T14:40:01.762Z] debug vscode got message from code-server {"type":"socket"},
[2021-12-08T14:40:01.762Z] debug protocol Initiating handshake... {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:01.909Z] debug got latest version {"latest":"3.12.0"},
[2021-12-08T14:40:01.909Z] debug comparing versions {"current":"3.12.0","latest":"3.12.0"},
[2021-12-08T14:40:01.992Z] debug protocol Handshake completed {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:01.993Z] debug exthost Connecting... {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:01.994Z] debug exthost Getting NLS configuration... {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:01.994Z] debug vscode 1 active exthost connection(s),
[2021-12-08T14:40:01.994Z] debug exthost Spawning extension host... {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:02.000Z] debug exthost Waiting for handshake... {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:03.408Z] debug exthost Handshake completed {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:03.409Z] debug exthost Sending socket {"token":"ae998576-6676-4c13-bdaa-974e75fa2dee"},
[2021-12-08T14:40:39.815Z] debug 3 active connections,

## Screenshot

![image](https://user-images.githubusercontent.com/44616229/145228614-1bb3ba74-bf9f-459f-959f-d967c6a59ec5.png)
![image](https://user-images.githubusercontent.com/44616229/145229708-e22c4422-da6e-4ba1-89cb-73a6a1480168.png)

## Notes

This issue can be reproduced in VS Code: Unknown, haven't tried.

**Comment by pheetr** [comment]
I've since come across the [FAQ entry](https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace) talking about the lack of MS extension marketplace.
This being said, the issue appears to still be applicable, as the data displayed appears to be outdated even compared to the Open VSX Registry ([Python example](https://open-vsx.org/extension/ms-python/python)) and I suppose some information should be displayed on the extension pages.

**Comment by jsjoeio** [comment]
This is due to the fact that we use a custom extension marketplace and sometimes extensions fall out of date (Python is a common one). 4.0.0 will use the Open VSX registry by default. 

In the meantime, we suggest using the environment variables to install from Open VSX. See the docs [here](https://coder.com/docs/code-server/latest/FAQ#how-do-i-use-my-own-extensions-marketplace).

Closing since this is working as expected.
