### ISSUE TITLE
linux version of rg binary included in recent mac os release package

### ISSUE THREAD

**Issue by joelhock** [cdr/code-server#496]
- code-server v1.696-vsc1.33.0
- mac os x 10.14.2

## Description
cmd-p quick search does not work on the recent mac package with a fresh user data directory because the package has the linux version of the `rg` binary.  So, you get "No results found." for all searches.

Also can cause transient issue where server bails on startup with 
```
INFO  Starting shared process [1/5]...
INFO  Starting shared process [2/5]... {"error":"P is not defined"}
/Users/travis/build/codercom/code-server/packages/server/out/cli.js:518
***************************************************************************** */var r,i=this&&this.__assign||function(){return(i=Object.assign||function(e){for(var t,n=1,r=arguments.length;n<r;n++)for(var i in t=arguments[n])Object.prototype.hasOwnProperty.call(t,i)&&(e[i]=t[i]);return e}).apply(this,arguments)},o=this&&this.__generator||function(e,t){var n,r,i,o,a={label:0,sent:function(){if(1&i[0])throw i[1];return i[1]},trys:[],ops:[]};return o={next:s(0),throw:s(1),return:s(2)},"function"==typeof Symbol&&(o[Symbol.iterator]=function(){return this}),o;function s(o){return function(s){return function(o){if(n)throw new TypeError("Generator is already executing.");for(;a;)try{if(n=1,r&&(i=2&o[0]?r.return:o[0]?r.throw||((i=r.return)&&i.call(r),0):r.next)&&!(i=i.call(r,o[1])).done)return i;switch(r=0,i&&(o=[2&o[0],i.value]),o[0]){case 0:case 1:i=o;break;case 4:return a.label++,{value:o[1],done:!1};case 5:a.label++,r=o[1],o=[0];continue;ca

Error: "Shared process" is already retrying
    at o.run (/Users/travis/build/codercom/code-server/packages/server/out/cli.js:518:2096531)
    at Object.run (/Users/travis/build/codercom/code-server/packages/server/out/cli.js:518:2096099)
    at ChildProcess.on.e (/Users/travis/build/codercom/code-server/packages/server/out/cli.js:518:2093316)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

## Steps to Reproduce

1. start code with new user data directory, because the correct `rg` binary may be in place from installs of previous releases that included the correct binary, e.g.: `code-server1.696-vsc1.33.0-darwin-x64/code-server --user-data-dir this_dir_doesnt_exist --extensions-dir ~/.vscode/extensions`
1. the server may fail to start with the error code above.  or, if it does start, search will not work.  or just look at the file directly:
```
$ this_dir_doesnt_exist/dependencies/rg
-bash: foo/dependencies/rg: cannot execute binary file: Exec format error
$ file foo/dependencies/rg
this_dir_doesnt_exist/dependencies/rg: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=6071d8258757947bc45d235054734b278a3c226d, stripped

**Comment by kylecarbs** [comment]
Will fix. This is due to an overlook in our CI process. Thanks for the report!

**Comment by nol166** [comment]
This also seems to happen if you remove the code-server directory from `.local/share`

**Comment by code-asher** [comment]
I believe the new CI script should be building this correctly now but I haven't had an opportunity to test on Mac yet.

**Comment by sr229** [comment]
@code-asher I have a mac test environment that I borrowed so I'll check if that works now.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
