### ISSUE TITLE
code server crashes once in a while with another docker container writing a file through a shared file system

### ISSUE THREAD

**Issue by leckie-chn** [cdr/code-server#559]
- `code-server` version:  1.792-vsc1.33.1
- OS Version:  Ubuntu 16.04

## Description

code server web page crushes once in a while. 
here's the log from `render${timestamps}.log`
```
[2019-04-22 02:21:11.266] [renderer20190422022100350] [error] Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at n.e.getDataNode (https://stcagl-116:8443/f2dd3d.bundle.js:60:1889043)
    at n.e.updateWidth (https://stcagl-116:8443/f2dd3d.bundle.js:60:1885859)
    at e.updateWidth (https://stcagl-116:8443/f2dd3d.bundle.js:67:1329559)
    at https://stcagl-116:8443/f2dd3d.bundle.js:67:1340595
    at e.fire (https://stcagl-116:8443/f2dd3d.bundle.js:16:14094)
    at t.render (https://stcagl-116:8443/f2dd3d.bundle.js:38:363083)
    at t.notifyExtensionsRegistered (https://stcagl-116:8443/f2dd3d.bundle.js:38:360068)
    at https://stcagl-116:8443/f2dd3d.bundle.js:38:356548
    at Array.forEach (<anonymous>)
    at https://stcagl-116:8443/f2dd3d.bundle.js:38:356519
```

## Steps to Reproduce

1. open code-server in background: `nohup code-server --cert=$HOME/.certs/code-server.crt --cert-key=$HOME/.certs/code-server.key > /tmp/code-server.log 2>&1 &`
2. open a docker container, with shared file system with `-v`: `docker run -it -v ./:/mnt/hello /bin/bash`
3. run `some long running program > stdout.log` in docker container
4. open `stdout.log` in code server

suppose `some long running program` continues to render log to `stdout.log`. Then once in a while the code-server webpage will lose connection. But is able to reconnect after refresh.

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
