### ISSUE TITLE
Exception uncatched

### ISSUE THREAD

**Issue by Illyasviels** [cdr/code-server#632]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: Ubuntu16.04 / 18.04

## Description

```
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn [as _spawn] (child_process.js:538:9)
    at t.async (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34598)
    at e.exports (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34099)
    at e (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:32722)
    at Timeout.u [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:33015)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

## Steps to Reproduce

1. Create a droplet from DigitalOcean.
2. Install Ubuntu 16.04/ 18.10.
3. Follow instructions.
4. Error occured.

**Comment by Illyasviels** [comment]
I found it memory usage overflow.
