### ISSUE TITLE
workspaces not working?

### ISSUE THREAD

**Issue by jots** [cdr/code-server#687]
- `code-server` version: v1.939-vsc1.33.1
- OS Version: ubuntu

## Description

I have a .code-workspace file in a directory,  when I open the directory I'm prompted with :
"This folder contains a workspace file 'zzz.code-workspace'. Do you want to open it? Learn more about workspace files."
I click on "open workspace" button and nothing happens.  In the developer tools console I see this when I click the button:
```
 ERR not implemented: Error: not implemented
    at e.openWindow (http://127.0.0.1:8443/ide.main.92c1f4.js:60:1648115)
    at t.openWindow (http://127.0.0.1:8443/ide.main.92c1f4.js:60:6355629)
    at Object.run (http://127.0.0.1:8443/ide.main.92c1f4.js:60:1359655)
    at t._actionCallback (http://127.0.0.1:8443/ide.main.92c1f4.js:53:282278)
    at t.e.run (http://127.0.0.1:8443/ide.main.92c1f4.js:16:96194)
    at t.runAction (http://127.0.0.1:8443/ide.main.92c1f4.js:16:96868)
    at t.runAction (http://127.0.0.1:8443/ide.main.92c1f4.js:60:1185322)
    at t.run (http://127.0.0.1:8443/ide.main.92c1f4.js:16:96676)
    at http://127.0.0.1:8443/ide.main.92c1f4.js:60:6183093
    at e.fire (http://127.0.0.1:8443/ide.main.92c1f4.js:16:14094)
```
How can I use workspaces with code-server?  If not possible, what is a good alternative?

**Comment by vnijs** [comment]
It seems this functionality has not yet been implemented for code-server (https://github.com/cdr/code-server/issues/490). I agree this would be great to have though

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
