### ISSUE TITLE
terminal doesnt load

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#804]
![image](https://user-images.githubusercontent.com/12135498/59976809-fa4a1600-95fb-11e9-8e6b-2a3b3e6d4e54.png)

**Comment by Dj-jom2x** [comment]
```
WARN  stderr {"data":"(node:4167) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
WARN  stderr {"data":"Error: /tmp/.nbinkkhZL9-spdlog.node: failed to map segment from shared object\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:754:18)\n    at Module.load (internal/modules/cjs/loader.js:611:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:542:3)\n    at Module.require (internal/modules/cjs/loader.js:649:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at bindings (/node_modules/bindings/bindings.js:81:44)\n    at Object.<anonymous> (/node_modules/spdlog/index.js:3:35)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)\n    at Module.load (internal/modules/cjs/loader.js:611:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:542:3)\n    at Module.require (internal/modules/cjs/loader.js:649:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.spdlog (/src/packages/server/build/bootstrap-fork.js.gz:288720:18)\n    at __webpack_require__ (/src/packages/server/build/bootstrap-fork.js.gz:26:30)\n    at Object.createSpdLogService (/src/packages/server/build/bootstrap-fork.js.gz:154372:29)\n    at main (/src/packages/server/build/bootstrap-fork.js.gz:73348:88)\n    at /src/packages/server/build/bootstrap-fork.js.gz:73451:9\n    at Generator.next (<anonymous>)\n    at fulfilled (/src/packages/server/build/bootstrap-fork.js.gz:23310:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n"}
WARN  stderr {"data":"TypeError: _spdlog.setAsyncMode is not a function\n    at Object.createSpdLogService (/src/packages/server/build/bootstrap-fork.js.gz:154373:21)\n    at instantiationService.invokeFunction.accessor (/src/packages/server/build/bootstrap-fork.js.gz:73371:101)\n    at InstantiationService.invokeFunction (/src/packages/server/build/bootstrap-fork.js.gz:150815:27)\n    at main (/src/packages/server/build/bootstrap-fork.js.gz:73367:26)\n    at /src/packages/server/build/bootstrap-fork.js.gz:73451:9\n    at Generator.next (<anonymous>)\n    at fulfilled (/src/packages/server/build/bootstrap-fork.js.gz:23310:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n"}
INFO  Connected to shared process

```

**Comment by Dj-jom2x** [comment]
I don't understand why this is happening

**Comment by Dj-jom2x** [comment]
on my other server it works on this new one with same dist not working.. the terminal only

**Comment by Dj-jom2x** [comment]
i found the bug if you install cyberpanel 

you will got that.. also your terminal will not work

**Comment by Dj-jom2x** [comment]
building it and running
docker run -it -p 0.0.0.0:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth

seems to work..

**Comment by Dj-jom2x** [comment]
the only problem i see is this spam msg

```

Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/service-worker.js'
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'
5e19f81ddd89ea36466fa1cbError: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'
INFO  WebSocket opened / {"client":1,"ip":"112.211.148.119"}
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/service-worker.js'
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/__webpack_hmr'

```

**Comment by deansheather** [comment]
Webpack HMR is the hot reloading functionality in webpack. You should be able to disable it in webpack config, or I think it should be disabled by default if you set `NODE_ENV=production` before building the binary.
