### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 16696294. Received 16702498

### ISSUE THREAD

**Issue by wenerme** [cdr/code-server#825]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: `Linux a13e28d652b9 4.19.53-0-vanilla #1-Alpine SMP Wed Jun 19 15:06:10 UTC 2019 x86_64 Linux`

## Description

```
$ code-server -d ~/.config/vsc -N -H --disable-telemetry -p 8008
internal/buffer.js:53
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 16696294. Received 16702498
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32BE (internal/buffer.js:196:5)
    at Function.fromBuffer (nbin.js:1:3737)
    at Object.<anonymous> (nbin.js:1:2075)
    at r (nbin.js:1:222)
    at nbin.js:1:1021
    at nbin.js:1:1030
    at NativeModule.compile (internal/bootstrap/loaders.js:362:7)
    at NativeModule.require (internal/bootstrap/loaders.js:174:18)
    at internal/modules/cjs/loader.js:47:14
```

## Steps to Reproduce

1. build by https://github.com/alpinelinux/aports/pull/9263/files
2. start with `code-server -d ~/.config/vsc -N -H --disable-telemetry -p 8008`

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
