### ISSUE TITLE
Activating extension `x` failed:  Cannot find module 'lodash'

### ISSUE THREAD

**Issue by nikovirtala** [cdr/code-server#982]
- `code-server` version: code-server2.1478-vsc1.38.1-linux-x86_64
- OS Version: Debian 9.11, Google Cloud Shell, Linux cs-6000-devshell-vm-990a08f3-9eef-4668-b552-97db4745c349 4.19.44+ #1 SMP Tue Jul 30 23:06:26 PDT 2019 x86_64 GNU/Linux

## Description

Activation fails for two of my extensions:

+ Formatting Toggle (tombonnike.vscode-status-bar-format-toggle)
+ Terraform (mauve.terraform)

In console, I can see error messages like below for both extensions:

```
notificationsAlerts.ts:20 Activating extension 'mauve.terraform' failed: Cannot find module 'lodash'.
onDidNotificationChange @ notificationsAlerts.ts:20
(anonymous) @ editorWidgets.ts:96
fire @ event.ts:572
addNotification @ notifications.ts:156
notify @ preferencesSearch.ts:522
_showMessageToUser @ feedback.ts:296
_logOrShowMessage @ feedback.ts:307
(anonymous) @ labelService.ts:192
(anonymous) @ errors.ts:199
n @ errors.ts:199
$onExtensionActivationError @ labelService.ts:190
_doInvokeHandler @ terminalTab.ts:298
_invokeHandler @ terminalTab.ts:281
_receiveRequest @ terminalTab.ts:204
_receiveOneMessage @ terminalTab.ts:133
(anonymous) @ terminalTab.ts:23
fire @ event.ts:572
fire @ ipc.net.ts:569
_receiveMessage @ ipc.net.ts:811
(anonymous) @ ipc.net.ts:638
fire @ event.ts:572
acceptChunk @ ipc.net.ts:314
(anonymous) @ ipc.net.ts:273
(anonymous) @ remoteAgentFileSystemChannel.ts:52
fire @ event.ts:572
_fileReader.onload @ remoteAgentFileSystemChannel.ts:16
map.ts:38 [Extension Host] Activating extension `mauve.terraform` failed:  Cannot find module 'lodash'
t.log @ map.ts:38
$logExtensionHostMessage @ macLinuxKeyboardMapper.ts:1065
_doInvokeHandler @ terminalTab.ts:298
_invokeHandler @ terminalTab.ts:281
_receiveRequest @ terminalTab.ts:204
_receiveOneMessage @ terminalTab.ts:133
(anonymous) @ terminalTab.ts:23
fire @ event.ts:572
fire @ ipc.net.ts:569
_receiveMessage @ ipc.net.ts:811
(anonymous) @ ipc.net.ts:638
fire @ event.ts:572
acceptChunk @ ipc.net.ts:314
(anonymous) @ ipc.net.ts:273
(anonymous) @ remoteAgentFileSystemChannel.ts:52
fire @ event.ts:572
_fileReader.onload @ remoteAgentFileSystemChannel.ts:16
map.ts:38 [Extension Host] Here is the error stack:  Error: Cannot find module 'lodash'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:593:15)
	at Function.Module._load (internal/modules/cjs/loader.js:519:25)
	at Function.t._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:660)
	at Function.i._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
	at Function.n._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
	at Module.require (internal/modules/cjs/loader.js:649:17)
	at require (internal/modules/cjs/helpers.js:22:18)
	at Object.<anonymous> (/home/niko_virtala/.local/share/code-server/extensions/mauve.terraform-1.4.0/out/src/autocompletion/completion-provider.js:3:11)
	at Module._compile (internal/modules/cjs/loader.js:701:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
	at Module.load (internal/modules/cjs/loader.js:611:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
	at Function.Module._load (internal/modules/cjs/loader.js:542:3)
	at Function.t._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:660)
	at Function.i._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
	at Function.n._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
	at Module.require (internal/modules/cjs/loader.js:649:17)
	at require (internal/modules/cjs/helpers.js:22:18)
	at Object.<anonymous> (/home/niko_virtala/.local/share/code-server/extensions/mauve.terraform-1.4.0/out/src/extension.js:12:31)
	at Module._compile (internal/modules/cjs/loader.js:701:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
	at Module.load (internal/modules/cjs/loader.js:611:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
	at Function.Module._load (internal/modules/cjs/loader.js:542:3)
	at Function.t._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:660)
	at Function.i._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
	at Function.n._load (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
	at Module.require (internal/modules/cjs/loader.js:649:17)
	at require (internal/modules/cjs/helpers.js:22:18)
	at Function.i [as __$__nodeRequire] (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/loader.js:32:381)
	at f._loadCommonJSModule (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:632)
	at f._doActivateExtension (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:27)
	at f._activateExtension (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:654:108)
	at f.<anonymous> (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:937)
	at Generator.next (<anonymous>)
	at /src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:83
	at new Promise (<anonymous>)
	at i (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:862)
	at Object.actualActivateExtension (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:639)
	at p._activateExtension (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:21)
	at r.length.Promise.all.s.map.e (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:628)
	at Array.map (<anonymous>)
	at p._activateExtensions (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:616)
	at p.activateByEvent (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:477)
	at f._activateByEvent (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:775)
	at _readyToRunExtensions.wait.then.t (/src/build/code-server2.1478-vsc1.38.1-linux-x86_64-built/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:547)
	at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Steps to Reproduce

1. Start Code Server
2. Install an extension

**Comment by kylecarbs** [comment]
Likely an issue with our extension registry. Extensions are located in `.local/share/code-server/extensions` (by default). You can `npm install` inside each extension dir to fix this for now.

**Comment by nikovirtala** [comment]
Thanks! This seem to work at least for "Formatting Toggle" extension. Terraform still fails but it is looking for an app insights key that does not exist in the extension repository, so not a problem of `code-server` at all.

**Comment by scarolan** [comment]
Also observed this with VSC 1.39.1 and Terraform extension 1.4.0

**Comment by sr229** [comment]
@scarolan Workaround it to run a `yarn` or `npm install` in the extension dir. It seems our repo compiles extensions incompletely or wrong.

**Comment by mashirozx** [comment]
maybe the same issue?

> Activating extension 'felixfbecker.php-intellisense' failed: Cannot find module '/home/code-server/data/extensions/felixfbecker.php-intellisense-1.5.4/out/extension'.

OS:  Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-64-generic x86_64)
code-server: code-server2.1650-vsc1.39.2-linux-x86_64

**Comment by scarolan** [comment]
Thanks @sr229 - we're actually running from a docker container that doesn't have npm or yarn installed.  We'll wait for a fix from upstream.

**Comment by nhooyr** [comment]
See #1299
